* added mulle-project-new-rep and mulle-project-github-description

diff --git a/mulle-project-clib-json b/mulle-project-clib-json
--- a/mulle-project-clib-json
+++ b/mulle-project-clib-json
@@ -17,6 +17,7 @@ fi
 print_flags()
 {
    echo "   -o <file>   : output JSON to file"
+   echo "   -a <file>   : add additional file to sources"
 
    options_technical_flags_usage "       : "
 }
@@ -69,7 +70,7 @@ get_repo()
 {
    log_entry "get_repo" "$@"
 
-   local scheme domain host scm user repo branch tag
+   local domain user repo
    local remote
 
    .for remote in `git remote 2> /dev/null`
@@ -120,48 +121,15 @@ print_name()
 }
 
 
-get_description_4()
-{
-   rexekutor head -4 "README.md" \
-   | grep -E '^####' \
-   | sed -e 's/^####//' -e 's/^ //g'
-}
-
-
-get_description_2()
-{
-   rexekutor sed -e '/^[[:space:]]*$/d' "README.md" \
-   | head -2 \
-   | tail -1
-}
-
-
-get_description()
-{
-   log_entry "get_description" "$@"
-
-   if [ ! -z "${DESC}" ]
-   then
-      echo "${DESC}"
-   else
-      if [ -f "README.md" ]
-      then
-         if ! get_description_4
-         then
-            get_description_2
-         fi
-      fi
-   fi
-}
-
-
 print_description()
 {
    log_entry "print_description" "$@"
 
    local text
 
-   text="`get_description | tr -d -c '[[:print:]]'`"
+   include "project::settings"
+
+   text="`project::setting::get_description | tr -d -c '[[:print:]]'`"
    r_trim_whitespace "${text}"
    printf "%s" "${INDENT}\"description\" : \"${RVAL}\"";
 }
@@ -232,13 +200,15 @@ print_repo()
 
 print_sources()
 {
+   local aux_sources="$1"
+
    local qualifier
 
    if [ -d .mulle/share/match ]
    then
       qualifier='(TYPE_MATCHES header OR TYPE_MATCHES source OR CATEGORY_MATCHES clib) AND NOT CATEGORY_MATCHES no_clib'
       sources="`rexekutor mulle-match ${MULLE_TECHNICAL_FLAGS} \
-                                      ${MULLE_MATCH_FLAGS}list --qualifier  "${qualifier}" `"
+                                      ${MULLE_MATCH_FLAGS}list --qualifier "${qualifier}" `"
    else
       # cheat and hack
       sources="`find src -name "*.h" \
@@ -248,6 +218,18 @@ print_sources()
                       -o -name "*.aam" \
                       -o -name "*.m" `"
    fi
+
+   .foreachline line in ${aux_sources}
+   .do
+      if [ ! -e "${line}" ]
+      then
+         fail "\"${line}\" does not exist"
+      fi
+      r_add_unique_line "${sources}" "${line}"
+      sources="${RVAL}"
+   .done
+
+   sources="`LC_ALL=C sort -f <<< "${sources}" `"
 
    local sep
 
@@ -259,6 +241,7 @@ print_sources()
       printf "%s\"%s\"" "${sep}" "${line}"
       sep=","$'\n'"${INDENT}${INDENT}"
    .done
+
    printf "\n%s" "${INDENT}]"
 }
 
@@ -275,26 +258,17 @@ print_dependencies()
 
    sep="\\n${INDENT}${INDENT}"
 
-   local alias_tag
-   local aliases
-   local branch
    local domain
-   local host
    local line
    local name
-   local print_tag
    local repo
-   local s
-   local scheme
-   local scm
-   local tag
    local url
    local user
    local xtag
 
    .foreachline line in ${lines}
    .do
-      name="${line%%;*}"
+#      name="${line%%;*}"
       line="${line#*;}"
       xtag="${line%%;*}"
       url="${line#*;}"
@@ -335,6 +309,8 @@ print_json()
 {
    log_entry "print_json" "$@"
 
+   local aux_sources="$1"
+
    INDENT="   "
    echo "{"
       print_name
@@ -349,7 +325,7 @@ print_json()
       printf ",\n"
       print_repo
       printf ",\n"
-      print_sources
+      print_sources "${aux_sources}"
 
       local dependencies
 
@@ -376,6 +352,8 @@ print_json()
 main()
 {
    local OPTION_OUTPUT_FILE="-"
+   local OPTION_SOURCES
+
    #
    # simple flag handling
    #
@@ -401,6 +379,14 @@ main()
             shift
 
             OPTION_OUTPUT_FILE="$1"
+         ;;
+
+         -a|--add-source)
+            [ $# -eq 1 ] && fail "Missing argument to \"$1\""
+            shift
+
+            r_add_line "${OPTION_SOURCES}" "$1"
+            OPTION_SOURCES="${RVAL}"
          ;;
 
          --version)
@@ -447,9 +433,9 @@ main()
 
    if [ "${OPTION_OUTPUT_FILE}" = '-' ]
    then
-      print_json
+      print_json "${OPTION_SOURCES}"
    else
-      text="`print_json`" || return 1
+      text="`print_json "${OPTION_SOURCES}"`" || return 1
       redirect_exekutor "${OPTION_OUTPUT_FILE}" echo "${text}"
    fi
 }
diff --git a/mulle-project-versioncheck b/mulle-project-versioncheck
--- a/mulle-project-versioncheck
+++ b/mulle-project-versioncheck
@@ -16,11 +16,12 @@ fi
 
 print_flags()
 {
-   echo "   -f            : force operation"
-   echo "   --reflect     : write into ${PROJECT_SOURCE_DIR:-src}/reflect"
-   echo "   --update-only : only write if file exists"
+   echo "   -f                : force operation"
+   echo "   --reflect         : write into ${PROJECT_SOURCE_DIR:-src}/reflect"
+   echo "   --update-only     : only write if file exists"
+   echo "   --fetch-if-needed : fetch dependencies if missing"
 
-   options_technical_flags_usage "         : "
+   options_technical_flags_usage "            : "
 }
 
 
@@ -126,8 +127,6 @@ emit_include_file()
    local main_identifier="$1"
    local stashdir="$2"
 
-   local dependency
-   local name
 
    echo "/*
  *   This file will be regenerated by \`mulle-project-versioncheck\`.
@@ -137,15 +136,25 @@ emit_include_file()
 #   echo "#ifndef ${main_identifier}_CHECK_H__"
 #   echo "#define ${main_identifier}_CHECK_H__"
 
-   shell_disable_glob
-   IFS=$'\n'
-   for name in `mulle-sde dependency list -- --output-no-header --force-format '%a\n' | sort`
-   do
+   local dependencies
+   local dependency
+   local name
+
+   #
+   # avoid getting embedded stuff into this
+   #
+   dependencies="`mulle-sde dependency list --qualifier "MATCHES build" -- \
+                                            --output-no-header \
+                                            --force-format '%a\n' | sort`"
+   .foreachline name in ${dependencies}
+   .do
       r_basename "${name}"
       if [ "${RVAL}" = "${name}" ]
       then
+         log_verbose "Emit check for \"\${stash_dir}/${name}\""
          dependency="${stashdir}/${name}"
       else
+         log_verbose "Emit check for \"${name}\""
          dependency="${name}"
       fi
 
@@ -155,30 +164,15 @@ emit_include_file()
          cd "${dependency}" 2> /dev/null && emit_version_check
       )
       fi
-   done
-   shell_enable_glob; IFS="${DEFAULT_IFS}"
+   .done
 #   echo "#endif"
 }
 
 main()
 {
-   local MULLE_FLAG_MAGNUM_FORCE='NO'
-
-   # technical flags
-   local MULLE_TRACE
-   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
-   local MULLE_FLAG_LOG_LOCAL='NO'
-   local MULLE_FLAG_LOG_DEBUG='NO'
-   local MULLE_FLAG_LOG_EXEKUTOR='NO'
-   local MULLE_FLAG_LOG_FLUFF='NO'
-   local MULLE_FLAG_LOG_SCRIPTS='NO'
-   local MULLE_FLAG_LOG_SETTINGS='NO'
-   local MULLE_FLAG_LOG_VERBOSE='NO'
-   local MULLE_FLAG_LOG_MERGE='NO'
-   local MULLE_TRACE_POSTPONE='NO'
-
    local OPTION_REFLECT
    local OPTION_UPDATE
+   local OPTION_FETCH
 
    #
    # simple flag handling
@@ -198,6 +192,10 @@ main()
 
          -h*|--help|help)
             usage
+         ;;
+
+         --fetch-if-needed)
+            OPTION_FETCH='YES'
          ;;
 
          --reflect)
@@ -251,9 +249,17 @@ main()
 
    if [ ! -d "${stashdir}" ]
    then
-      _log_warning "There is no ${stashdir#${MULLE_USER_PWD}/} directory here, nothing to do
+      if [ "${OPTION_FETCH}" = 'YES' ]
+      then
+         exekutor mulle-sde fetch || exit 1
+      fi
+
+      if [ ! -d "${stashdir}" ]
+      then
+         _log_warning "There is no ${stashdir#${MULLE_USER_PWD}/} directory here, nothing to do
 ${C_INFO}Run mulle-sde fetch if this is unexpected."
-      return 0
+         return 0
+      fi
    fi
 
    if [ "${OPTION_REFLECT}" != 'YES' ]
