* mulle-project-all supplies ${GITHUB_NAME} now * mulle-project-properties-plist now also outputs amalgamated and embedded dependencies * mulle-project-clib-json now pulls the license infor from cola/properties.plist if available

diff --git a/mulle-project-all b/mulle-project-all
--- a/mulle-project-all
+++ b/mulle-project-all
@@ -60,13 +60,14 @@ print_flags()
    --all               : execute in all projects,subprojects,tests
    --directory <dir>   : enter subdirectory, before executing project command
    --exec ...          : evaluate command line in the project
+   --if-exists <file>  : ignore project if <file> does not exist
    --if <expr>         : ignore project if shell expression evaluates to false
    --ignore <name>     : ignore a project from REPOS, multiples are possible
    --others            : also execute in other projects, like demo
-   --output-no-header  : don't visually separate command output
    --parallel          : execute operations in parallel
    --repos-file <f>    : REPOS file to use
    --sde               : only execute in mulle-sde projects
+   --skip-until <s>    : skip projects in REPOS until <s>
    --strict            : errors preempt
    --tests             : also execute in test directories
 EOF
@@ -74,7 +75,6 @@ EOF
    then
       cat <<EOF
    --eval ...          : a less convenient legacy variant of exec
-   --if-exists <file>  : ignore project if <file> does not exist
    --lenient           : lenient operation, errors don't preempt (default)
    --main-project      : also execute in main project
    --no-cd             : do not change to project directory
@@ -82,8 +82,8 @@ EOF
    --only-main-project : only execute in main project (default)
    --only-tests        : only execute in tests directories
    --only-subprojects  : only execute in subprojects project
+   --output-no-header  : don't visually separate command output
    --skip-from <s>     : skip projects in REPOS starting with <s>
-   --skip-until <s>    : skip projects in REPOS until <s>
    --skip-past <s>     : skip projects in REPOS until and including <s>
    --sublime <file>    : create a "Sublime Text" project from REPOS
    --subprojects       : also execute in subprojects
@@ -117,6 +117,7 @@ Usage:
       NAME            : basename of the directory
       DIRECTORY       : path of the directory
       PROJECT_NAME    : name of the main project
+      GITHUB_NAME     : basename of parent directory / basename directory
 
       SUBPROJECT_NAME : set if its a subproject
       OTHER_NAME      : set if its an other project test
@@ -131,7 +132,7 @@ Examples:
    Create a .gitattributes file for projects under git control:
       mulle-project-all --if "[ -d .git ]" cp /tmp/.gitattributes .
 
-   Generate include statements for all projects:
+   Generate include statements for all projects (expansion only with \${}):
       mulle-project-all -s --exec printf '%s\\n' '#include <\${NAME}.h>'
 
    If there is no "REPOS" file, mulle-project-all will look for mulle-sde
@@ -225,6 +226,9 @@ shell_it()
    [ -z "${DIRECTORY}" ] && return
 
    (
+      r_physicalpath "${DIRECTORY}"
+      DIRNAME="${RVAL}"
+
       if [ "${OPTION_CD}" = 'YES' ]
       then
          rexekutor cd "${DIRECTORY}" || exit 1
@@ -232,11 +236,14 @@ shell_it()
          rexekutor [ -d "${DIRECTORY}" ] || exit 1
       fi
 
-      r_dirname "${DIRECTORY}"
+      r_dirname "${DIRNAME}"
       DIRNAME="${RVAL}"
 
       r_basename "${DIRECTORY}"
       NAME="$RVAL"
+
+      r_basename "${DIRNAME}"
+      GITHUB_NAME="${RVAL}/${NAME}"
 
       if [ ! -z "${OPTION_IF}" ]
       then
@@ -247,6 +254,7 @@ shell_it()
               SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
               OTHER_NAME="'${OTHER_NAME}'" \
               TEST_NAME="'${TEST_NAME}'" \
+              GITHUB_NAME="'${GITHUB_NAME}'" \
               eval_exekutor "${OPTION_IF}"
          then
             log_info "Skip ${C_RESET_BOLD}$1"
@@ -336,6 +344,7 @@ shell_it()
                        SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
                        OTHER_NAME="'${OTHER_NAME}'" \
                        TEST_NAME="'${TEST_NAME}'" \
+                       GITHUB_NAME="'${GITHUB_NAME}'" \
                        "$@"
          return $?
       fi
@@ -542,6 +551,10 @@ r_repos_contents()
 
    if [ ! -z "${skipfrom}" ]
    then
+      if ! grep -q -F -x "${skipfrom}" <<< "${repos}"
+      then
+         fail "--skip-from \"${skipfrom}\", repository not found"
+      fi
       r_escaped_sed_pattern "${skipfrom}"
       skipfrom="/^${RVAL}\$/"
    fi
@@ -550,6 +563,11 @@ r_repos_contents()
 
    if [ ! -z "${skipuntil}" ]
    then
+      if ! grep -q -F -x "${skipuntil}" <<< "${repos}"
+      then
+         fail "--skip-until \"${skipuntil}\", repository not found"
+      fi
+
       first="${skipuntil}"
       r_escaped_sed_pattern "${skipuntil}"
       skipuntil="/^${RVAL}\$/"
@@ -557,6 +575,11 @@ r_repos_contents()
 
    if [ ! -z "${skippast}" ]
    then
+      if ! grep -q -F -x "${skippast}" <<< "${repos}"
+      then
+         fail "--skip-past \"${skippast}\", repository not found"
+      fi
+
       first=
       r_escaped_sed_pattern "${skippast}"
       skipuntil="/^${RVAL}\$/"  # sic
@@ -877,6 +900,11 @@ main()
                     "${OPTION_SKIP_UNTIL}" \
                     "${OPTION_SKIP_PAST}"
    repos="${RVAL}"
+
+   if [ -z "${REPOS}" ]
+   then
+      log_info "Nothing to do"
+   fi
 
    if [ "${OPTION_PRINT}" = 'YES' ]
    then
diff --git a/mulle-project-properties-plist b/mulle-project-properties-plist
--- a/mulle-project-properties-plist
+++ b/mulle-project-properties-plist
@@ -229,11 +229,19 @@ find_description()
    fi
    log_debug "MULLE_FETCH_SEARCH_PATH: ${MULLE_FETCH_SEARCH_PATH}"
 
+   # hack (?) for amalgamated clib dependencies
+   case "${projectname}" in
+      *@*)
+         projectname="${projectname%%@*}"
+      ;;
+   esac
+
    .foreachpath item in ${MULLE_FETCH_SEARCH_PATH}
    .do
       r_filepath_concat "${item}" "${projectname}" "README.md"
       filename="${RVAL}"
 
+      # MEMO: too oldschool, should look into properties
       if get_readme_description "${filename}"
       then
          .break
@@ -354,8 +362,9 @@ print_dependencies()
 {
    log_entry "print_dependencies" "$@"
 
-   local sep="$1"
-   local qualifier="$2"
+   local title="$1"
+   local sep="$2"
+   local qualifier="$3"
 
 #   if search_plist "dependencies" "${sep}"
 #   then
@@ -372,19 +381,20 @@ print_dependencies()
    # ignore embedded
    lines=`rexekutor mulle-sde ${MULLE_TECHNICAL_FLAGS} \
                               ${MULLE_SDE_FLAGS} \
-                        dependency list -- \
-                           --dedupe-mode url-filename \
-                           --qualifier "${qualifier}" \
-                           --output-eval \
-                           --output-no-column \
-                           --output-no-header \
-                           --force-format "%a;%u\\n"` || exit 1
+                        dependency list --columnar \
+                                        -- \
+                                           --dedupe-mode url-filename \
+                                           --qualifier "${qualifier}" \
+                                           --output-eval \
+                                           --output-no-column \
+                                           --output-no-header \
+                                           --force-format "%a;%u\\n"` || exit 1
    if [ -z "${lines}" ]
    then
       return
    fi
 
-   printf "dependencies =\n("
+   printf "${title} =\n("
 
    local name
    local url
@@ -397,7 +407,7 @@ print_dependencies()
    sep2=$'\n'
    .foreachline line in ${lines}
    .do
-      printf "${sep2}   {\n" "${sep}"
+      printf "${sep2}   {\n"
       name="${line%%;*}"
       url="${line#*;}"
 
@@ -434,18 +444,38 @@ print_dependencies()
 
 
 
+_print_plist()
+{
+   log_entry "_print_plist" "$@"
+
+   local qualifier="$1"
+   local amalgamated_qualifier="$2"
+   local embedded_qualifier="$3"
+
+   print_project ';'
+   print_dependencies 'dependencies' ';' "${qualifier}"
+   if [ ! -z "${amalgamated_qualifier}" ]
+   then
+      print_dependencies 'amalgamated' ';' "${amalgamated_qualifier}"
+   fi
+   if [ ! -z "${embedded_qualifier}" ]
+   then
+      print_dependencies 'embedded' ';' "${embedded_qualifier}"
+   fi
+
+
+}
+
+
 print_plist()
 {
    log_entry "print_plist" "$@"
 
-   local qualifier="$1"
+   printf '{\n'
 
-   printf "{\n"
+   _print_plist "$@" | sed 's/^/   /'
 
-   print_project ";"                    | sed 's/^/   /'
-   print_dependencies "" "${qualifier}" | sed 's/^/   /'
-
-   printf "}\n"
+   printf '}\n'
 }
 
 
@@ -455,6 +485,8 @@ main()
    local OPTION_CHECKSUM='YES'
    local OPTION_MULLE='NO'
    local OPTION_QUALIFIER='MATCHES share AND MATCHES build'
+   local OPTION_AMALGAMATED_QUALIFIER='NOT MATCHES share-shirk AND NOT MATCHES build'
+   local OPTION_EMBEDDED_QUALIFIER='MATCHES share-shirk AND NOT MATCHES build'
 
    MULLE_TEMPLATE_COMPOSER_SEARCHPATH="${MULLE_TEMPLATE_COMPOSER_SEARCHPATH:-\
 "includes\
@@ -511,6 +543,28 @@ main()
             OPTION_QUALIFIER="$1"
          ;;
 
+         --amalgamated-qualifier)
+            [ $# -eq 1 ] && fail "Missing argument to \"$1\""
+            shift
+
+            OPTION_AMALGAMATED_QUALIFIER="$1"
+         ;;
+
+         --embedded-qualifier)
+            [ $# -eq 1 ] && fail "Missing argument to \"$1\""
+            shift
+
+            OPTION_EMBEDDED_QUALIFIER="$1"
+         ;;
+
+         --no-amalgamated)
+            OPTION_AMALGAMATED_QUALIFIER=""
+         ;;
+
+         --no-embedded)
+            OPTION_EMBEDDED_QUALIFIER=""
+         ;;
+
          --version)
             printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
             exit 0
@@ -541,9 +595,13 @@ main()
 
    if [ "${OPTION_OUTPUT_FILE}" = '-' ]
    then
-      print_plist "${OPTION_QUALIFIER}"
+      print_plist "${OPTION_QUALIFIER}" \
+                  "${OPTION_AMALGAMATED_QUALIFIER}" \
+                  "${OPTION_EMBEDDED_QUALIFIER}"
    else
-      text="`print_plist "${OPTION_QUALIFIER}"`" || return 1
+      text="`print_plist "${OPTION_QUALIFIER}" \
+                         "${OPTION_AMALGAMATED_QUALIFIER}" \
+                         "${OPTION_EMBEDDED_QUALIFIER}" `" || return 1
       redirect_exekutor "${OPTION_OUTPUT_FILE}" echo "${text}"
    fi
 }
