* new script mulle-homebrew-releasenotes promises to update the RELEASENOTES.md file from git comments, that are prefixed with * * new script mulle-homebrew-debian for shell script distribution

diff --git a/mulle-homebrew-version b/mulle-homebrew-version
--- a/mulle-homebrew-version
+++ b/mulle-homebrew-version
@@ -33,7 +33,7 @@
 usage()
 {
    cat <<EOF >&2
-Usage: mulle-homebrew-get-version [options] [projectname]
+Usage: mulle-homebrew-version [options] [projectname]
 
    Determine the project version.
 
@@ -42,6 +42,8 @@ Options:
    --language <name>     : project language, (c, obj, cpp, bash etc)
    --versionname <name>  : version variable name
    --versionfile <file>  : file containing version
+   --increment <value>   : amount to add to version
+   --write               : update versionfile with incremented value
 EOF
    exit 1
 }
@@ -54,11 +56,36 @@ fail()
 }
 
 
+mulle_homebrew_version_init()
+{
+   #
+   # prefer local mulle-homebrew if available
+   # Do not embed it anymore!
+   #
+   if [ -z "`command -v mulle-homebrew-env`" ]
+   then
+      cat <<EOF >&2
+mulle-homebrew-env not found in PATH.
+Visit the homepage for installation instructions:
+   https://github.com/mulle-nat/mulle-homebrew
+EOF
+      exit 1
+   fi
+
+   INSTALLED_MULLE_HOMEBREW_VERSION="`mulle-homebrew-env version`" || exit 1
+   LIBEXEC_DIR="`mulle-homebrew-env libexec-path`" || exit 1
+
+   . "${LIBEXEC_DIR}/mulle-version.sh" || exit 1
+}
+
+
 main()
 {
    local directory
 
    local OPTION_READ_INFO="YES"
+   local OPTION_WRITE="NO"
+   local OPTION_ADD_PATCH="NO"
 
    local OPTION_VERSIONNAME
    local OPTION_VERSIONFILE
@@ -68,6 +95,17 @@ main()
       case "$1" in
          --no-info)
             OPTION_READ_INFO="NO"
+         ;;
+
+         --increment)
+            [ $# -eq 1 ] && fail "missing argument to $1"
+            shift
+
+            OPTION_ADD_PATCH="$1"
+         ;;
+
+         --write)
+            OPTION_WRITE="YES"
          ;;
 
          --language)
@@ -136,25 +174,6 @@ main()
    VERSIONFILE="${OPTION_VERSIONFILE:-${VERSIONFILE}}"
 
    #
-   # prefer local mulle-homebrew if available
-   # Do not embed it anymore!
-   #
-   if [ -z "`command -v mulle-homebrew-env`" ]
-   then
-      cat <<EOF >&2
-mulle-homebrew-env not found in PATH.
-Visit the homepage for installation instructions:
-   https://github.com/mulle-nat/mulle-homebrew
-EOF
-      exit 1
-   fi
-
-   INSTALLED_MULLE_HOMEBREW_VERSION="`mulle-homebrew-env version`" || exit 1
-   LIBEXEC_DIR="`mulle-homebrew-env libexec-path`" || exit 1
-
-   . "${LIBEXEC_DIR}/mulle-version.sh" || exit 1
-
-   #
    # these can usually be deduced, if you follow the conventions
    #
    if [ -z "${LANGUAGE}" ]
@@ -176,19 +195,40 @@ EOF
 
       if [ -f VERSION ]
       then
-         VERSION="`head -1 VERSION`"
+         VERSIONFILE="VERSION"
+         VERSIONNAME=""
+         VERSION="`head -1 "${VERSIONFILE}"`"
       else
          VERSION="`get_project_version "${VERSIONFILE}" "${VERSIONNAME}"`" || exit 1
          if [ -z "${VERSION}" ]
          then
-            VERSION="`get_project_version "src/version.h" "${VERSIONNAME}"`" || exit 1
+            VERSIONFILE="src/version.h"
+            VERSION="`get_project_version "${VERSIONFILE}" "${VERSIONNAME}"`" || exit 1
          fi
       fi
+   else
+      VERSIONFILE=
    fi
 
    if [ -z "${VERSION}" ]
    then
       fail "Could not figure out the version for PROJECT=\"${PROJECT}\", LANGUAGE=\"${LANGUAGE}\", VERSIONNAME=\"${VERSIONNAME}\", VERSIONFILE=\"${VERSIONFILE}\". (hint: specify VERSIONNAME, VERSIONFILE)"
+   fi
+
+   if [ "${OPTION_ADD_PATCH}" != "NO" ]
+   then
+      if [ -z "${VERSIONFILE}" ]
+      then
+         fail "Don't know how to increment version"
+      fi
+
+      VERSION="`project_version_add "${VERSION}" "${OPTION_ADD_PATCH}"`" || exit 1
+
+      if [ "${OPTION_WRITE}" = "YES" ]
+      then
+         set_project_version "${VERSION}" "${VERSIONFILE}" "${VERSIONNAME}"
+         return $?
+      fi
    fi
 
    echo "${VERSION}"
@@ -197,5 +237,7 @@ EOF
 
 MULLE_EXECUTABLE="`basename -- $0`"
 MULLE_BOOTSTRAP_FAIL_PREFIX="${MULLE_EXECUTABLE}"
+
+mulle_homebrew_version_init
 
 main "$@"
