* new scripts mulle-project-travis-ci-prerelease mulle-project-prerelease mulle-project-local-travis mulle-project-add-missing-branch-identifier

diff --git a/mulle-project-debian b/mulle-project-debian
--- a/mulle-project-debian
+++ b/mulle-project-debian
@@ -17,9 +17,10 @@ Usage:
    There is no signing involved.
 
    Options:
-      --root <path> : default is /usr
-      --no-update   : don't execute did-update.sh in the taps directory
-      --no-publish  : don't publish to tap
+      --root <path>    : default is /usr
+      --debname <name> : repository name parameter for did-update.sh (main)
+      --no-update      : don't execute did-update.sh in the taps directory
+      --no-publish     : don't publish to tap
 EOF
    exit 1
 }
@@ -65,43 +66,43 @@ write_control()
 }
 
 
-create_debian()
+r_create_debian()
 {
-   log_entry "create_debian" "$@"
+   log_entry "r_create_debian" "$@"
 
    local directory
 
    directory="${PROJECT}_${VERSION}"
 
-   rmdir_safer -rf "/tmp/${directory}"
+   rmdir_safer "/tmp/${directory}"
    mkdir_if_missing "/tmp/${directory}/DEBIAN"
 
    log_verbose "Run mulle-install --prefix \"/tmp/${directory}${OPTION_ROOT}\""
 
    exekutor mulle-make install -k --prefix "/tmp/${directory}${OPTION_ROOT}" >&2 || exit 1
 
-   redirect_exekutor "/tmp/${directory}/DEBIAN/control" write_control
+   redirect_exekutor "/tmp/${directory}/DEBIAN/control" write_control || exit 1
 
    # brew install dpkg
    (
-      cd "/tmp" ;
+      exekutor cd "/tmp"
 
       # we use gzip, because on trusty xz is not always available
       # and trusty is used on travis-ci
 
       # building packages on OSX can be shit, if something plunks down
       # .DS_Store files
-      find "${directory}" \( -name ._.DS_Store -o -name .DS_Store \) -exec rm -f {} \;
+      exekutor find "${directory}" \( -name ._.DS_Store -o -name .DS_Store \) -exec rm -f {} \;
 
-      dpkg-deb -Zgzip -b "${directory}" >&2 || exit 1
+      exekutor dpkg-deb -Zgzip -b "${directory}" >&2 || exit 1
 
       if [ "${OPTION_REMOVE_TMP}" = 'YES' ]
       then
-         rm -rf "${directory}"
+         rmdir_safer "${directory}"
       fi
-   )
+   ) || exit 1
 
-   echo "/tmp/${directory}.deb"
+   RVAL="/tmp/${directory}.deb"
 }
 
 
@@ -121,8 +122,13 @@ main()
    then
       . .mulle/etc/project/formula-info.sh
    fi
+   if [ -f ".mulle/etc/project/publisher-info.sh" ]
+   then
+      . .mulle/etc/project/publisher-info.sh
+   fi
 
-   EXE_DIR="`dirname -- "$0"`"
+   r_dirname "$0"
+   EXE_DIR="${RVAL}"
    LIBEXEC_DIR="`"${EXE_DIR}/mulle-project-env" libexec-dir`" || exit 1
 
    while [ $# -ne 0 ]
@@ -136,6 +142,13 @@ main()
       case "$1" in
          -h|--help|help)
             usage
+         ;;
+
+         --debname)
+            [ $# -eq 1 ] && fail "missing argument to $1"
+            shift
+
+            DEBIAN_REPOSITORY="$1"
          ;;
 
          --no-update)
@@ -197,13 +210,42 @@ main()
 
    options_setup_trace "${MULLE_TRACE}"
 
-   # assume mulle-project debian is called from ./bin/release.sh
+   #
+   # parameters sent by mulle-project-distribute
+   # we only care about DEBIAN_REPOSITORY as we already have code for
+   # the rest...
+   #
+   # PROJECT
+   # NAME
+   # VERSION
+   # DEPENDENCIES
+   # BUILD_DEPENDENCIES
+   # HOMEPAGE_URL
+   # DESC
+   # ARCHIVE_URL
+   # DEBIAN_DEPENDENCIES
+   # DEBIAN_REPOSITORY
 
-   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-publisher.sh"
+   log_debug "Arguments: $*"
+
+   [ $# -eq 0 ] || shift  # PROJECT
+   [ $# -eq 0 ] || shift  # NAME
+   [ $# -eq 0 ] || shift  # VERSION
+   [ $# -eq 0 ] || shift  # DEPENDENCIES
+   [ $# -eq 0 ] || shift  # BUILD_DEPENDENCIES
+   [ $# -eq 0 ] || shift  # HOMEPAGE_URL
+   [ $# -eq 0 ] || shift  # DESC
+   [ $# -eq 0 ] || shift  # ARCHIVE_URL
+   [ $# -eq 0 ] || shift  # DEBIAN_DEPENDENCIES
+
+   DEBIAN_REPOSITORY="${1:-${DEBIAN_REPOSITORY}}" ; [ $# -eq 0 ] || shift  # DEBIAN_REPOSITORY
+
+   [ $# -eq 0 ] || shift  # TAG
 
    if [ -z "${PROJECT}" ]
    then
-      PROJECT="`basename -- "$PWD"`"
+      r_basename "${PWD}"
+      PROJECT="${RVAL}"
    fi
 
    if [ -z "`command -v dpkg-deb`" ]
@@ -219,7 +261,8 @@ main()
       esac
    fi
 
-   debianfile="`create_debian`" || exit 1
+   r_create_debian || exit 1
+   debianfile="${RVAL}"
 
    if [ "${OPTION_PUBLISH}" = 'YES' ]
    then
@@ -227,19 +270,23 @@ main()
 
       if [ -d "${DEBIAN_DISTS}" ]
       then
-         mkdir "${DEBIAN_DISTS}/all" 2> /dev/null
+         exekutor mkdir "${DEBIAN_DISTS}/all" 2> /dev/null
 
          log_info "Publishing \"${debianfile}\"..."
-         mv "${debianfile}" "${DEBIAN_DISTS}/all/"
+         exekutor mv "${debianfile}" "${DEBIAN_DISTS}/all/"
 
          if [ "${OPTION_UPDATE}" = 'YES' ] && [ -x "${DEBIAN_DISTS}/did-update.sh" ]
          then
             (
-              log_info "Executing ./did-update.sh in ..."
+              log_info "Executing ./did-update.sh ${DEBIAN_REPOSITORY:-main} in ..."
 
-              cd "${DEBIAN_DISTS}"
-              # let some script take over
-              ./did-update.sh "${debianfile}"
+              #
+              # this calls srcO/debian-software/did-upload.sh
+              #
+              r_basename "${debianfile}"
+
+              exekutor cd "${DEBIAN_DISTS}" && \
+              exekutor ./did-update.sh "${DEBIAN_REPOSITORY:-main}" "${RVAL}"
             ) || exit 1
          fi
       else
diff --git a/mulle-project-distribute b/mulle-project-distribute
--- a/mulle-project-distribute
+++ b/mulle-project-distribute
@@ -34,7 +34,7 @@
 #    https://github.com/mulle-sde/mulle-project
 #
 # Run this somewhat like this (for real: remove -n):
-#    mulle-project-release -v -n --publisher mulle-nat --publisher-tap mulle-kybernetik/software/
+#    mulle-project-distribute -v -n --publisher mulle-nat --publisher-tap mulle-kybernetik/software/
 #
 [ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
@@ -44,9 +44,12 @@ usage()
    cat <<EOF >&2
 Usage: mulle-project-distribute [options]
 
-   Distribute the project via github, homebrew, debian.
+   Distribute the project via github and homebrew. Debian is indirectly
+   supported by calling mulle-project-debian.
 
 Options:
+   --branch <name>   : branch to push to (release)
+   --debname <name>  : debian repository name (main)
    --no-git          : suppress git operations (implies --no-post-release)
    --no-formula      : suppress formula operations (implies --no-post-release)
    --no-formula-push : do not publish the formula to github
@@ -143,7 +146,19 @@ __environment_main()
       DEPENDENCIES="`egrep -v '^#' .DEPENDENCIES`"
    fi
 
-   MULLE_KYBERNETIK_TAP="${MULLE_KYBERNETIK_TAP:-mulle-kybernetik/software/}"
+   TAP_USER="${TAP_USER:-mulle-kybernetik}"
+   TAP_NAME="${TAP_NAME:-software}"
+
+   MULLE_TAP_USER="${MULLE_TAP_USER:-${TAP_USER}}"
+   MULLE_TAP_NAME="${MULLE_TAP_NAME:-${TAP_NAME}}"
+
+   CODEON_TAP_USER="${CODEON_TAP_USER:-codeon-gmbh}"
+   CODEON_TAP_NAME="${CODEON_TAP_NAME:-software}"
+
+   # TODO: so much hard coding, should put this outside into
+   # source-able files
+
+   MULLE_KYBERNETIK_TAP="${MULLE_KYBERNETIK_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${MULLE_KYBERNETIK_TAP}" in
       */)
       ;;
@@ -153,7 +168,7 @@ __environment_main()
       ;;
    esac
 
-   MULLE_SDE_TAP="${MULLE_SDE_TAP:-mulle-kybernetik/software/}"
+   MULLE_SDE_TAP="${MULLE_SDE_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${MULLE_SDE_TAP}" in
       */)
       ;;
@@ -164,7 +179,7 @@ __environment_main()
    esac
 
 
-   MULLE_NAT_TAP="${MULLE_NAT_TAP:-mulle-kybernetik/software/}"
+   MULLE_NAT_TAP="${MULLE_NAT_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${MULLE_NAT_TAP}" in
       */)
       ;;
@@ -174,7 +189,7 @@ __environment_main()
       ;;
    esac
 
-   MULLE_C_TAP="${MULLE_C_TAP:-mulle-kybernetik/software/}"
+   MULLE_C_TAP="${MULLE_C_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${MULLE_C_TAP}" in
       */)
       ;;
@@ -184,7 +199,7 @@ __environment_main()
       ;;
    esac
 
-   MULLE_OBJC_TAP="${MULLE_OBJC_TAP:-mulle-kybernetik/software/}"
+   MULLE_OBJC_TAP="${MULLE_OBJC_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${MULLE_OBJC_TAP}" in
       */)
       ;;
@@ -194,7 +209,57 @@ __environment_main()
       ;;
    esac
 
-   BUILDTOOLS_TAP="${BUILDTOOLS_TAP:-mulle-kybernetik/software/}"
+   MULLE_CONCURRENT_TAP="${MULLE_CONCURRENT_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
+   case "${MULLE_CONCURRENT_TAP}" in
+      */)
+      ;;
+
+      *)
+         MULLE_CONCURRENT_TAP="${MULLE_CORE_TAP}/"
+      ;;
+   esac
+
+   MULLE_CORE_TAP="${MULLE_CORE_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
+   case "${MULLE_CORE_TAP}" in
+      */)
+      ;;
+
+      *)
+         MULLE_CORE_TAP="${MULLE_CORE_TAP}/"
+      ;;
+   esac
+
+   MULLE_FOUNDATION_TAP="${MULLE_FOUNDATION_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
+   case "${MULLE_FOUNDATION_TAP}" in
+      */)
+      ;;
+
+      *)
+         MULLE_FOUNDATION_TAP="${MULLE_FOUNDATION_TAP}/"
+      ;;
+   esac
+
+   MULLE_WEB_TAP="${MULLE_WEB_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
+   case "${MULLE_WEB_TAP}" in
+      */)
+      ;;
+
+      *)
+         MULLE_WEB_TAP="${MULLE_WEB_TAP}/"
+      ;;
+   esac
+
+   MULLE_SCION_TAP="${MULLE_SCION_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
+   case "${MULLE_SCION_TAP}" in
+      */)
+      ;;
+
+      *)
+         MULLE_SCION_TAP="${MULLE_SCION_TAP}/"
+      ;;
+   esac
+
+   BUILDTOOLS_TAP="${BUILDTOOLS_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${BUILDTOOLS_TAP}" in
       */)
       ;;
@@ -204,7 +269,7 @@ __environment_main()
       ;;
    esac
 
-   TOOLS_TAP="${TOOLS_TAP:-mulle-kybernetik/software/}"
+   TOOLS_TAP="${TOOLS_TAP:-${MULLE_TAP_USER}/${MULLE_TAP_NAME}/}"
    case "${TOOLS_TAP}" in
       */)
       ;;
@@ -224,12 +289,39 @@ __environment_main()
       ;;
    esac
 
+   CODEON_TAP="${CODEON_TAP:-${CODEON_TAP_USER}/${CODEON_TAP_NAME}/}"
+   case "${CODEON_TAP}" in
+      */)
+      ;;
 
-   # where to grab the archive off
-   ARCHIVE_URL="${ARCHIVE_URL:-https://github.com/${PUBLISHER}/${PROJECT}/archive/${VERSION}.tar.gz}"
+      *)
+         CODEON_TAP="${CODEON_TAP}/"
+      ;;
+   esac
 
-   # written into formula for project, will be evaled
-   HOMEPAGE_URL="${HOMEPAGE_URL:-https://github.com/${PUBLISHER}/${PROJECT}}"
+   # --- GIT ---
+
+   if [ -z "${VERSION}" ]
+   then
+      fail "Could not figure out the version. (hint: use VERSIONNAME, VERSIONFILE)"
+   fi
+
+   # tag to tag your release
+   if [ "${OPTION_TAG}" = "YES" ]
+   then
+      TAG="${TAG:-${TAG_PREFIX}${VERSION}${TAG_SUFFIX}}"
+   else
+      TAG=""
+   fi
+
+   # git remote to push to, usually origin
+   ORIGIN="${ORIGIN:-origin}"
+
+   # git remote to push to, usually github, can be empty
+   GITHUB="${GITHUB:-github}"
+
+   # git branch to release to, source is always current
+   BRANCH="${BRANCH:-release}"
 
 
    # --- HOMEBREW TAP ---
@@ -245,31 +337,19 @@ __environment_main()
 
    if [ ! -z "${PUBLISHER_TAP}" ]
    then
-      tmp="`basename -- ${PUBLISHER_TAP}`"
+      r_basename "${PUBLISHER_TAP}"
+      tmp="${RVAL}"
       HOMEBREW_TAP="${HOMEBREW_TAP:-${TAPS_LOCATION}/homebrew-${tmp}}"
    fi
 
    RBFILE="${RBFILE:-${NAME}.rb}"
 
+  # where to grab the archive off
+   ARCHIVE_URL="${ARCHIVE_URL:-https://github.com/${PUBLISHER}/${PROJECT}/archive/${TAG}.tar.gz}"
 
-   # --- GIT ---
+   # written into formula for project, will be evaled
+   HOMEPAGE_URL="${HOMEPAGE_URL:-https://github.com/${PUBLISHER}/${PROJECT}}"
 
-   if [ -z "${VERSION}" ]
-   then
-      fail "Could not figure out the version. (hint: use VERSIONNAME, VERSIONFILE)"
-   fi
-
-   # tag to tag your release
-   TAG="${TAG:-${TAG_PREFIX}${VERSION}}"
-
-   # git remote to push to, usually origin
-   ORIGIN="${ORIGIN:-origin}"
-
-   # git remote to push to, usually github, can be empty
-   GITHUB="${GITHUB:-github}"
-
-   # git branch to release to, source is always current
-   BRANCH="${BRANCH:-release}"
 }
 
 
@@ -283,6 +363,9 @@ main()
    local OPTION_DO_GIT_RELEASE=""
    local OPTION_DO_GENERATE_FORMULA=""
    local OPTION_DO_POST_RELEASE=""
+   local OPTION_TAG="YES"
+
+   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-user-files-settings.sh" "$@"   || exit 1
 
    while [ $# -ne 0 ]
    do
@@ -323,6 +406,10 @@ main()
             OPTION_DO_GENERATE_FORMULA='NO'
          ;;
 
+         --no-tag)
+            OPTION_TAG="NO"
+         ;;
+
          --no-latest-tag)
             OPTION_LATEST_TAG=""
          ;;
@@ -351,22 +438,28 @@ main()
             BUILDTOOLS_TAP="$1"
          ;;
 
-         --tools-tap)
-            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
-            shift
-            TOOLS_TAP="$1"
-         ;;
-
          --branch)
             [ $# -eq 1 ] && fail "missing parameter for \"$1\""
             shift
             BRANCH="$1"
          ;;
 
+         --debname|--debian-repository)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+            DEBIAN_REPOSITORY="$1"
+         ;;
+
          --dependency-tap)
             [ $# -eq 1 ] && fail "missing parameter for \"$1\""
             shift
             DEPENDENCY_TAP="$1"
+         ;;
+
+         --codeon-tap)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+            CODEON_TAP="$1"
          ;;
 
          --github)
@@ -405,6 +498,7 @@ main()
             PUBLISHER_TAP="$1"
          ;;
 
+
          --tag)
             [ $# -eq 1 ] && fail "missing parameter for \"$1\""
             shift
@@ -415,6 +509,61 @@ main()
             [ $# -eq 1 ] && fail "missing parameter for \"$1\""
             shift
             TAG_PREFIX="$1"
+         ;;
+
+         --tag-suffix)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+            TAG_SUFFIX="$1"
+         ;;
+
+         --tap-name)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            TAP_NAME="$1"
+         ;;
+
+         --tap-user)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            TAP_USER="$1"
+         ;;
+
+         --codeon-tap-name)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            CODEON_TAP_NAME="$1"
+         ;;
+
+         --codeon-tap-user)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            CODEON_TAP_USER="$1"
+         ;;
+
+         --mulle-tap-name)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            MULLE_TAP_NAME="$1"
+         ;;
+
+         --mulle-tap-user)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            MULLE_TAP_USER="$1"
+         ;;
+
+
+         --tools-tap)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+            TOOLS_TAP="$1"
          ;;
 
          --taps-location)
@@ -432,9 +581,10 @@ main()
          --*)
             [ $# -eq 1 ] && fail "missing parameter for \"$1\""
 
-            varname="`sed 's/^..//' <<< "$1"`"
-            varname="`tr '-' '_' <<< "${varname}"`"
-            varname="`tr '[a-z]' '[A-Z]' <<< "${varname}"`"
+            varname="${1#..}" # not sure anymore what this does
+            varname="${varname//-/_}"
+            r_uppercase "${varname}"
+            varname="${RVAL}"
             if ! egrep -q -s '^[A-Z_][A-Z0-9_]*$' <<< "${varname}" > /dev/null
             then
                fail "invalid variable specification \"${varname}\", created by \"$1\""
@@ -460,14 +610,13 @@ main()
    then
       log_warning "No .mulle/etc/project folder found."
    fi
-
    #
    # order of includes is important its a bit weird coded, due to being
-   # old
+   # old. We slurp in user values before the parameters, so that these
+   # can be overridden by the parameters to the script
    #
-   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-user-files.sh" "$@"   || exit 1
+   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-user-files.sh" "$@"      || exit 1
    source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-version.sh" "$@"      || exit 1
-   source_file "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-publisher.sh" "$@"    || exit 1
 
   __environment_main
 
@@ -517,17 +666,24 @@ main()
       fail "Nothing to do! .mulle/etc/project/version-info.sh and .mulle/etc/project/formula-info.sh are missing"
    fi
 
+   local exit_or_continue_if_dry_run
+
+   exit_or_continue_if_dry_run="return"
+   if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' ]
+   then
+      exit_or_continue_if_dry_run=':'
+   fi
 
    if [ "${DO_GIT_RELEASE}" = 'YES' ]
    then
-     # do the release
-      git_verify_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || exit 1
+      # do the release
+      git_verify_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || ${exit_or_continue_if_dry_run} 1
 
       if [ "${VERIFY_ONLY}" != 'YES' ]
       then
          log_info "Git release..."
 
-         git_commit_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || exit 1
+         git_commit_main "${BRANCH}" "${ORIGIN}" "${TAG}" "${GITHUB}" "${OPTION_LATEST_TAG}" || ${exit_or_continue_if_dry_run}  1
       fi
    else
       log_fluff "No git release"
@@ -560,10 +716,11 @@ main()
                                 "${DESC}" \
                                 "${ARCHIVE_URL}" \
                                 "${HOMEBREW_TAP}" \
-                                "${RBFILE}"
+                                "${RBFILE}" \
+                                "${TAG}"
          then
             log_error "Homebrew generation failed!"
-            return 1
+            ${exit_or_continue_if_dry_run}  1
          fi
       fi
    else
@@ -576,12 +733,15 @@ main()
       if ! homebrew_push "${NAME}" \
                          "${VERSION}" \
                          "${HOMEBREW_TAP}" \
-                         "${RBFILE}"
+                         "${RBFILE}" \
+                         "${TAG}"
       then
          log_error "Homebrew formula push failed!"
-         return 1
+         ${exit_or_continue_if_dry_run} 1
       fi
    fi
+
+   DEBIAN_REPOSITORY="${DEBIAN_REPOSITORY:-main}"
 
    #
    # check if someone installed a post_release function
@@ -594,7 +754,8 @@ main()
          if [ "`type -t post_release`" = "function" ]
          then
             log_info "Post release..."
-            post_release "${PROJECT}" \
+            post_release ${MULLE_TECHNICAL_FLAGS} \
+                         "${PROJECT}" \
                          "${NAME}" \
                          "${VERSION}" \
                          "${DEPENDENCIES}" \
@@ -602,7 +763,9 @@ main()
                          "${HOMEPAGE_URL}" \
                          "${DESC}" \
                          "${ARCHIVE_URL}" \
-                         "${DEBIAN_DEPENDENCIES}"
+                         "${DEBIAN_DEPENDENCIES}" \
+                         "${DEBIAN_REPOSITORY}" \
+                         "${TAG}"
          else
             log_fluff "No post release"
          fi
