* mulle-replace does not bail anymore if it encounters a directory in the list of files to work on

diff --git a/mulle-replace b/mulle-replace
--- a/mulle-replace
+++ b/mulle-replace
@@ -30,7 +30,7 @@ print_flags()
    ## ADD YOUR FLAG DESCRIPTION HERE
    ##
 
-   options_technical_flags_usage "       : "
+   options_technical_flags_usage "         : "
 }
 
 
@@ -102,8 +102,8 @@ delete_line()
 
    if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' ]
    then
-      after="`eval_rexekutor sed "${sed_command}" "'${filename}'" `" || return 1
-      log_info "Changes"
+      after="`eval_rexekutor sed "${sed_command}" "'${filename}'" `"
+      log_info "Changes in ${C_RESET_BOLD}${filename}"
       rexekutor "${DIFF}" -b <( echo "${before}") <( echo "${after}" ) >&2
       return $?
    fi
@@ -123,7 +123,18 @@ delete_line()
       exekutor chmod +w "${filename}"
    fi
 
-   eval_rexekutor inplace_sed "${sed_command}" "${filename}" || return 1
+   local error
+
+   if ! "`{ error=$( eval_rexekutor inplace_sed "${sed_command}" "'${filename}'" 2>&1 >&3 3>&-); } 3>&1`"
+   then
+      if [ -d "${filename}" ]
+      then
+         log_verbose "${filename} is a directory"
+         return 0
+      fi
+      printf "%s\n" "${error}" >&2
+      return 1
+   fi
 
    if [ "${unprotect}" = 'YES' ]
    then
@@ -132,7 +143,7 @@ delete_line()
 
    if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
    then
-      log_verbose "Changes"
+      log_verbose "Changes in ${C_RESET_BOLD}${filename}"
       rexekutor "${DIFF}" -b <( echo "${before}") "${filename}" >&2
    fi
 }
@@ -180,7 +191,7 @@ replace()
 
    if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' -o "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' ]
    then
-      before="`rexekutor cat "${filename}"`"
+      before="`rexekutor cat "${filename}" 2> /dev/null`"
 
       if ! DIFF="${DIFF:-"`command -v diff`"}"
       then
@@ -190,8 +201,9 @@ replace()
 
    if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' ]
    then
-      after="`eval_rexekutor sed "${sed_command}" "'${filename}'" `" || return 1
-      log_info "Changes"
+      after="`eval_rexekutor sed "${sed_command}" "'${filename}'" `"
+
+      log_info "Changes in ${C_RESET_BOLD}${filename}"
       rexekutor "${DIFF}" -b <( echo "${before}") <( echo "${after}" ) >&2
       return 0
    fi
@@ -211,7 +223,18 @@ replace()
       exekutor chmod +w "${filename}"
    fi
 
-   eval_rexekutor inplace_sed "${sed_command}" "${filename}" || return 1
+   local error
+
+   if ! { error=$( eval_rexekutor inplace_sed "${sed_command}" "'${filename}'" 2>&1 >&3 3>&-); } 3>&1
+   then
+      if [ -d "${filename}" ]
+      then
+         log_verbose "${filename} is a directory"
+         return 0
+      fi
+      printf "%s\n" "${error}" >&2
+      return 1
+   fi
 
    if [ "${unprotect}" = 'YES' ]
    then
@@ -220,7 +243,7 @@ replace()
 
    if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
    then
-      log_verbose "Changes"
+      log_verbose "Changes in ${C_RESET_BOLD}${filename}"
       rexekutor "${DIFF}" -b <( echo "${before}") "${filename}" >&2
    fi
 
