* use mulle-bashfunctions more and some more improvements

diff --git a/mulle-project-releasenotes b/mulle-project-releasenotes
--- a/mulle-project-releasenotes
+++ b/mulle-project-releasenotes
@@ -34,6 +34,8 @@
 
 usage()
 {
+   [ "$#" -ne 0 ] && log_error "$1"
+
    cat <<EOF >&2
 Usage: mulle-project-releasenotes [options] [releasenotes]
 
@@ -46,6 +48,7 @@ Usage: mulle-project-releasenotes [options] [releasenotes]
 Options:
    -a                       : prepend notes to first releasenote
    -f                       : overwrite existing releasenotes for version
+   --all                    : dump all releasenotes from the beginning
    --commit                 : git commit --amend --no-edit releasenotes
    --default-message <text> : text to use,if there are no suitable git comments
    --filter <executable>    : use something else than egrep to filter comments
@@ -63,15 +66,10 @@ EOF
 }
 
 
-fail()
-{
-   echo "Error:" "$*" >&2
-   exit 1
-}
-
-
 compute_markers()
 {
+   log_entry "compute_markers" "$@"
+
    local version="$1"
 
    local major
@@ -94,79 +92,141 @@ compute_markers()
 }
 
 
-escaped_sed_replacement()
+filter_releasenotes()
 {
-   sed -e 's|\\|\\\\|g' <<< "${1}"
+   log_entry "filter_releasenotes" "$@"
+
+   sed -n 's/'${RELEASENOTE_GREP}'\(.*\)/\1/p'
 }
 
 
-filter_releasenotes()
+get_releasenote_commits()
 {
-   sed -n 's/'${RELEASENOTE_GREP}'\(.*\)/\1/p'
+   log_entry "get_releasenote_commits" "$@"
+
+   if [ "${OPTION_ALL}" = "YES" ]
+   then
+      git_commits_from_start
+      return
+   fi
+
+   local start
+
+   start="${OPTION_TAG}"
+
+   if [ "${OPTION_MISSING}" = "YES" ]
+   then
+      if [ "${OPTION_INPUT}" = "-" ]
+      then
+         fail "no input specified"
+      fi
+
+      if [ ! -z "${start}" ]
+      then
+         fail "missing and start specified at same time"
+      fi
+
+      start="`get_latest_releasenote_version "${OPTION_INPUT}"`"
+      log_debug "latest releasenote version is \"${start}\""
+   fi
+
+   if [ -z "${start}" ]
+   then
+      start="`git_last_tag`"
+      log_debug "last tag is \"${start}\""
+      if [ -z "${start}" ]
+      then
+         start="`git_any_first_commit`"
+         log_debug "any first commit is \"${start}\""
+      fi
+   fi
+
+   log_debug "start is \"${start}\""
+
+   git_commits_from_tag "${start}"
+}
+
+
+determine_message()
+{
+   log_entry "determine_message" "$@"
+
+   local prefix="$1"
+   local defaultmessage="$2"
+
+   local message
+   local commits
+
+   commits="`get_releasenote_commits`"
+   log_debug "Commits: ${commits}"
+
+   message="`"${RELEASENOTE_FILTER}" <<< "${commits}"`"
+
+   if [ -z "${message}" ]
+   then
+       message="${defaultmessage}"
+   fi
+
+   #
+   # now prefix
+   #
+   if [ ! -z "${prefix}" ]
+   then
+      local pattern
+
+      pattern="`escaped_sed_pattern "${prefix}"`"
+      message="`sed "s/^/${pattern}/" <<< "${message}"`"
+   fi
+
+   echo "${message}"
+}
+
+
+markdown_escape_message()
+{
+   log_entry "markdown_escape_message" "$@"
+
+   #
+   # envelope underscore words as backticks
+   # also envelope lozenges
+   #
+   sed -e 's/\([^ ]*_[^ _]*\)/`\1`/g' \
+       -e 's/\(<[^<>]*>\)/`\1`/g'
 }
 
 
 emit_releasenotes()
 {
+   log_entry "emit_releasenotes" "$@"
+
    local version="$1"
    local markers="$2"
+   local prefix="$3"
+   local message="$4"
+   local defaultmessage="$5"
 
-   if [ -z "${OPTION_MESSAGE}" ]
+   if [ -z "${message}" ]
    then
-      local start="${OPTION_TAG}"
-
-      if [ "${OPTION_MISSING}" = "YES" ]
-      then
-         if [ "${OPTION_INPUT}" = "-" ]
-         then
-            fail "no input specified"
-         fi
-
-         if [ ! -z "${start}" ]
-         then
-            fail "missing and start specified at same time"
-         fi
-
-         start="`get_latest_releasenote_version "${OPTION_INPUT}"`"
-      fi
-
-      if [ -z "${start}" ]
-      then
-         start="`git_last_tag`"
-         if [ -z "${start}" ]
-         then
-            start="`git_any_first_commit`"
-         fi
-      fi
-
-      OPTION_MESSAGE="`git_commits_from_tag "${start}" | ${RELEASENOTE_FILTER}`"
-      if [ -z "${OPTION_MESSAGE}" ]
-      then
-          OPTION_MESSAGE="${OPTION_DEFAULT_MESSAGE}"
-      fi
-
-      #
-      # now prefix
-      #
-      if [ ! -z "${OPTION_PREFIX}" ]
-      then
-         local pattern
-
-         pattern="`escaped_sed_replacement "${OPTION_PREFIX}"`"
-         OPTION_MESSAGE="`sed "s/^/${pattern}/" <<< "${OPTION_MESSAGE}"`"
-      fi
+      message="`determine_message "${prefix}" "${defaultmessage}"`" || exit 1
    fi
 
-   cat <<EOF
+   if [ "${OPTION_MD_ESCAPE}" = "YES" ]
+   then
+      message="`markdown_escape_message <<< "${message}"`"
+   fi
+
+   exekutor cat <<EOF
 ${markers} ${version}
 
-${OPTION_MESSAGE}
+${message}
 EOF
 }
 
 
 copy_without_first_entry()
 {
+   log_entry "copy_without_first_entry" "$@"
+
    local header="$1"
 
    # remove old comments for same version
@@ -188,12 +248,12 @@ copy_without_first_entry()
             if egrep -s "^${markers} *" <<< "${line}"
             then
                state="copy"
-               echo "${line}"
+               exekutor echo "${line}"
             fi
          ;;
 
          copy)
-            echo "${line}"
+            exekutor echo "${line}"
          ;;
       esac
    done
@@ -202,34 +262,18 @@ copy_without_first_entry()
 
 copy_without_first_line()
 {
+   log_entry "copy_without_first_line" "$@"
+
    # also remove a first empty line if present
 
    sed '1d' | sed '/./,$!d'
 }
 
 
-mulle_project_releasenotes_init()
-{
-   if [ -z "`command -v mulle-project-env`" ]
-   then
-      cat <<EOF >&2
-   mulle-project-env not found in PATH.
-   Visit the homepage for installation instructions:
-      https://github.com/mulle-nat/mulle-project
-EOF
-      exit 1
-   fi
-
-   INSTALLED_MULLE_PROJECT_VERSION="`mulle-project-env version`" || exit 1
-   LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1
-
-   . "${LIBEXEC_DIR}/mulle-git.sh" || exit 1
-   . "${LIBEXEC_DIR}/mulle-version.sh" || exit 1
-}
-
-
 emit_prepended_notes_to_file()
 {
+   log_entry "emit_prepended_notes_to_file" "$@"
+
    local markers="$1"
    local notes="$2"
    local tmpfile="$3"
@@ -259,6 +303,8 @@ EOF
 
 get_latest_releasenote_version()
 {
+   log_entry "get_latest_releasenote_version" "$@"
+
    local filename
 
    if [ ! -f "${filename}" ]
@@ -274,6 +320,8 @@ get_latest_releasenote_version()
 
 merged_releasenotes()
 {
+   log_entry "merged_releasenotes" "$@"
+
    local markers="$1"
    local notes="$2"
    local version="$3"
@@ -314,7 +362,7 @@ merged_releasenotes()
             copy_without_first_line "${old_header}" < "${OPTION_INPUT}" > "${tmpfile}" || exit 1
          fi
       else
-         if [ "${OPTION_FORCE}" = "NO" ]
+         if [ "${MULLE_FLAG_MAGNUM_FORCE}" = "NO" ]
          then
             rm "${tmpfile}"
             fail "Releasenotes already contain a leading entry for \"${version}\""
@@ -329,7 +377,7 @@ merged_releasenotes()
       fi
       edited_header="YES"
    else
-      cp "${OPTION_INPUT}" "${tmpfile}" || exit 1
+      exekutor cp "${OPTION_INPUT}" "${tmpfile}" || exit 1
       edited_header="YES"
    fi
 
@@ -337,7 +385,7 @@ merged_releasenotes()
 
    if [ "${OPTION_KEEP_TMP}" = "NO" ]
    then
-      rm "${tmpfile}"
+      exekutor rm "${tmpfile}"
    fi
 }
 
@@ -351,7 +399,7 @@ main()
    local OPTION_APPEND="NO"
    local OPTION_DEFAULT_MESSAGE="Various small improvements"
    local OPTION_FIRST_PATCH="0"
-   local OPTION_FORCE="NO"
+   local MULLE_FLAG_MAGNUM_FORCE="NO"
    local OPTION_COMMIT="NO"
    local OPTION_INPUT=""
    local OPTION_KEEP_TMP="YES"
@@ -360,6 +408,8 @@ main()
    local OPTION_PREFIX="* "
    local OPTION_TAG=""
    local OPTION_COMMITFLAGS="--amend --no-edit"
+   local OPTION_ALL
+   local OPTION_MD_ESCAPE="YES"
 
    local custom_output="NO"
 
@@ -378,9 +428,22 @@ main()
       OPTION_FIRST_PATCH="`cat ".first_patch"`"
    fi
 
+   #
+   # simple option handling
+   #
    while [ $# -ne 0 ]
    do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
       case "$1" in
+         -h|--help|help)
+            usage
+         ;;
+
          -a|--append)
             OPTION_APPEND="YES"
          ;;
@@ -389,33 +452,33 @@ main()
             OPTION_COMMIT="YES"
          ;;
 
-         -f|--force)
-            OPTION_FORCE="YES"
+         --all)
+            OPTION_ALL="YES"
          ;;
 
          --filter)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             RELEASENOTE_FILTER="$1"
          ;;
 
          -g|--grep)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             RELEASENOTE_GREP="$1"
          ;;
 
          -m|--message)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             OPTION_MESSAGE="$1"
          ;;
 
          -dm|--default_message)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             OPTION_DEFAULT_MESSAGE="$1"
@@ -426,14 +489,14 @@ main()
          ;;
 
          -i|--input)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             OPTION_INPUT="$1"
          ;;
 
          -o|--output)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument to $1"
             shift
 
             OPTION_OUTPUT="$1"
@@ -447,22 +510,26 @@ main()
             OPTION_MISSING="YES"
          ;;
 
+         --no-md-escape)
+            OPTION_MD_ESCAPE="NO"
+         ;;
+
          --prefix)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             OPTION_PREFIX="$1"
          ;;
 
          --tag)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             OPTION_TAG="$1"
          ;;
 
          --version)
-            [ $# -eq 1 ] && fail "missing argument to $1"
+            [ $# -eq 1 ] && usage "missing argument for \"$1\""
             shift
 
             VERSION="$1"
@@ -476,16 +543,8 @@ main()
             OPTION_FIRST_PATCH="1"
          ;;
 
-         -h|--help)
-            usage
-         ;;
-
-         -t)
-            set -x
-         ;;
-
          -*)
-            usage
+            usage "unknown option \"$1\""
          ;;
 
          *)
@@ -495,6 +554,8 @@ main()
 
       shift
    done
+
+   options_setup_trace "${MULLE_TRACE}"
 
    case $# in
       0)
@@ -528,12 +589,12 @@ main()
 
    if [ -z "${VERSION}" ]
    then
-      VERSION="`mulle-project-version --no-tag-warning`" || fail "Could not figure out current version"
+      VERSION="`rexekutor mulle-project-version --no-tag-warning`" || fail "Could not figure out current version"
    fi
 
    if [ "${OPTION_COMMIT}" = "YES" ]
    then
-      if [ ! -z "`git status -s --untracked-files=no`" ]
+      if [ ! -z "`rexekutor git status -s --untracked-files=no`" ]
       then
          fail "git repository is not in a pristine state, can not commit"
       fi
@@ -542,8 +603,15 @@ main()
    local notes
    local markers
 
+   log_fluff "Version: ${VERSION}"
    markers="`compute_markers "${VERSION}"`"
-   notes="`emit_releasenotes "${VERSION}" "${markers}"`"
+
+   log_fluff "Markers: ${markers}"
+   notes="`emit_releasenotes "${VERSION}" \
+                             "${markers}" \
+                             "${OPTION_PREFIX}" \
+                             "${OPTION_MESSAGE}" \
+                             "${OPTION_DEFAULT_MESSAGE}" `"
 
    #
    # if no file is given, we don't merge
@@ -552,9 +620,9 @@ main()
    then
       if [ "${OPTION_OUTPUT}" = "-" ]
       then
-         echo "${notes}"
+         exekutor echo "${notes}"
       else
-         echo "${notes}" > "${OPTION_OUTPUT}" || exit 1
+         redirect_exekutor "${OPTION_OUTPUT}" echo "${notes}"  || exit 1
       fi
    else
       local result
@@ -563,9 +631,9 @@ main()
 
       if [ "${OPTION_OUTPUT}" = "-" ]
       then
-         echo "${result}"
+         exekutor echo "${result}"
       else
-         echo "${result}" > "${OPTION_OUTPUT}" || exit 1
+         redirect_exekutor "${OPTION_OUTPUT}" echo "${result}" || exit 1
       fi
    fi
 
@@ -574,15 +642,46 @@ main()
       changed="`git ls-files -m "${OPTION_OUTPUT}"`"
       if [ ! -z "${changed}" ]
       then
-         git commit ${OPTION_COMMITFLAGS} "${OPTION_OUTPUT}"
+         exekutor git commit ${OPTION_COMMITFLAGS} "${OPTION_OUTPUT}"
       fi
    fi
 }
 
 
-MULLE_EXECUTABLE="`basename -- $0`"
-MULLE_BUILDTOOLS_FAIL_PREFIX="${MULLE_EXECUTABLE}"
+########
+###
+### INIT
+###
+_init()
+{
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
+         echo "mulle-bashfunctions are not installed" >&2 && \
+      exit 1
+   fi
 
-mulle_project_releasenotes_init
+   # shellcheck source=../mulle-bashfunctions/src/mulle-bashfunctions.sh
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"
 
+   MULLE_PROJECT_LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1
+
+   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-git.sh" || exit 1
+   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-version.sh" || exit 1
+
+   #  set -e # more pain then gain in the end
+   #  set -u # doesn't work with my style
+
+   set -o pipefail
+}
+
+
+###
+### INIT
+###
+########
+
+
+_init "$@" # needs params
 main "$@"
diff --git a/mulle-project-sloppy-distribute b/mulle-project-sloppy-distribute
--- a/mulle-project-sloppy-distribute
+++ b/mulle-project-sloppy-distribute
@@ -32,25 +32,82 @@
 [ "${TRACE}" = "YES" ] && set -x && : "$0" "$@"
 
 
+show_function()
+{
+   declare -f "$1" | \
+      sed -e '1,2d' -e '$d' | \
+      sed -e 's/^    //' | \
+      sed -e 's/exekutor //g' | \
+      sed -e "s/&&/^  /g" | \
+      tr '^' '\n'
+}
+
 usage()
 {
    [ "$#" -ne 0 ] && log_error "$1"
 
    cat <<EOF >&2
 Usage:
-   mulle-homebrew-untag <tag>
+   ${MULLE_USAGE_NAME} <message>
 
-   Remove <tag> from local clone and all remotes.
+   A lazy and sloppy way to push out a patch. It does:
+
+   `show_function "sloppy_commit"`
+   `show_function "sloppy_push"`
 EOF
    exit 1
+}
+
+sloppy_commit()
+{
+   exekutor git add -u &&
+   exekutor git commit -m "* $*"
+}
+
+
+sloppy_push()
+{
+   exekutor mulle-project-version --increment-patch --write &&
+   [ ! -f "RELEASENOTES.md" ] || exekutor mulle-project-releasenotes RELEASENOTES.md &&
+   exekutor git add -u &&
+   exekutor git commit --amend --no-edit &&
+   exekutor mulle-project-distribute
+}
+
+
+sloppy_distribute()
+{
+   if [ $# -ne 0 ]
+   then
+      sloppy_commit "$@" || exit 1
+   fi
+
+   sloppy_push
+}
+
+
+git_is_clean()
+{
+   log_entry "git_is_clean" "$@"
+
+   local name
+
+   name="${1:-${PWD}}"
+
+   if [ ! -d .git ]
+   then
+      fail "\"${name}\" is not a git repository"
+   fi
+
+   local clean
+
+   clean=`git status -s --untracked-files=no`
+   [ -z "${clean}" ]
 }
 
 
 main()
 {
-   local ORIGIN="origin"
-   local OPTION_FORCE="NO"
-
    while [ $# -ne 0 ]
    do
       if options_technical_flags "$1"
@@ -64,16 +121,6 @@ main()
             usage
          ;;
 
-         -f)
-            OPTION_FORCE="YES"
-         ;;
-
-         --origin)
-            [ $# -eq 1 ] && usage "missing argument to \"$1\""
-            shift
-            ORIGIN="$1"
-         ;;
-
          -*)
             usage "unknown option \"$1\""
          ;;
@@ -82,78 +129,41 @@ main()
             break
          ;;
       esac
-      shift
    done
 
    options_setup_trace "${MULLE_TRACE}"
 
-   TAG="$1"
-
-   if [ -z "${TAG}" ]
+   untracked="`exekutor git ls-files --others --exclude-standard`"
+   if [ ! -z "${untracked}" ]
    then
-      usage
+      fail "There are still untracked files here, can't be that sloppy"
    fi
 
-   log_info "Trying to remove local tag"
-   git tag -d "$TAG" || [ "${OPTION_FORCE}" = "YES" ] || exit 1
+   if ! git_is_clean && [ $# -eq 0 ]
+   then
+      log_error "Need a commit message for the outstandig commits"
+      git status -s
+      exit 1
+   fi
 
-   # find .git folder (must exist, since git tag didn't fail)
-
-   while [ ! -d .git ]
-   do
-      cd ..
-      [ `pwd` = "/" ] && exit 1  # paranoia
-   done
-
-   local i
-   local remote
-
-   for i in .git/refs/remotes/*
-   do
-      remote="`fast_basename "${i}"`"
-      log_info "Trying to remove tag \"${TAG}\" on remote \"${remote}\""
-      exekutor git push "${remote}" ":${TAG}" # failure is OK
-   done
+   sloppy_distribute "$@"
 }
 
 
-########
-###
-### INIT
-###
 _init()
 {
    if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
    then
-      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
       [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
-         echo "mulle-bashfunctions are not installed" >&2 && \
-      exit 1
+         echo "mulle-bashfunctions-env not installed" >&2 && \
+         exit 1
    fi
 
-   # shellcheck source=../mulle-bashfunctions/src/mulle-bashfunctions.sh
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh"
-
-   if [ -z "`command -v mulle-project-env`" ]
-   then
-      cat <<EOF >&2
-mulle-project-env not found in PATH.
-Visit the homepage for installation instructions:
-      https://github.com/mulle-nat/mulle-project
-EOF
-      exit 1
-   fi
-
-   set -o pipefail
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
 }
 
-
-###
-### INIT
-###
-########
-
-
-_init "$@" # needs params
+_init "$@"
 main "$@"
+
 
diff --git a/mulle-project-version b/mulle-project-version
--- a/mulle-project-version
+++ b/mulle-project-version
@@ -34,6 +34,8 @@
 
 usage()
 {
+   [ "$#" -ne 0 ] && log_error "$1"
+
    cat <<EOF >&2
 Usage: mulle-project-version [options] [projectname]
 
@@ -70,39 +72,11 @@ EOF
 }
 
 
-fail()
-{
-   echo "Error:" "$*" >&2
-   exit 1
-}
-
-
-mulle_project_version_init()
-{
-   #
-   # prefer local mulle-project if available
-   # Do not embed it anymore!
-   #
-   if [ -z "`command -v mulle-project-env`" ]
-   then
-      cat <<EOF >&2
-mulle-project-env not found in PATH.
-Visit the homepage for installation instructions:
-   https://github.com/mulle-nat/mulle-project
-EOF
-      exit 1
-   fi
-
-   INSTALLED_MULLE_PROJECT_VERSION="`mulle-project-env version`" || exit 1
-   LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1
-
-   . "${LIBEXEC_DIR}/mulle-version.sh" || exit 1
-   . "${LIBEXEC_DIR}/mulle-git.sh" || exit 1
-}
-
 
 get_xcodeproj_version()
 {
+   log_entry "get_xcodeproj_version" "$@"
+
    local filename="$1/project.pbxproj"
 
    if [ ! -f "${filename}" ]
@@ -118,6 +92,8 @@ get_xcodeproj_version()
 
 get_version()
 {
+   log_entry "get_version" "$@"
+
    if [ "${OPTION_READ_XCODE_VERSION}" = "YES" -o "${OPTION_WRITE_XCODE_VERSION}" = "YES" ]
    then
       ACTUAL_XCODEPROJ="${OPTION_XCODEPROJ}"
@@ -149,20 +125,21 @@ get_version()
    then
       if [ -z "${LANGUAGE}" ]
       then
-         LANGUAGE="`get_language_from_directoryname "${DIRECTORY_NAME}"`" || exit 1
+         LANGUAGE="`get_language_from_directoryname "${DIRECTORY_NAME}"`"
+         log_verbose "LANGUAGE is \"${LANGUAGE}\""
       fi
 
       if [ -z "${VERSIONFILE}" ]
       then
-         VERSIONFILE="`get_header_from_project "${PROJECT}" "${LANGUAGE}"`" || exit 1
+         VERSIONFILE="`get_header_from_project "${PROJECT}" "${LANGUAGE}"`"
       fi
 
       if [ -z "${VERSIONNAME}" ]
       then
-         VERSIONNAME="`get_versionname_from_project "${PROJECT}"`" || exit 1
+         VERSIONNAME="`get_versionname_from_project "${PROJECT}"`"
       fi
 
-      if [ -f VERSION ]
+      if [ ! -f "${VERSIONFILE}" -a -f "VERSION" ]
       then
          VERSION="`egrep -v '^#' "VERSION"`"
          if [ ! -z "${VERSION}" ]
@@ -170,10 +147,10 @@ get_version()
             VERSIONFILE="VERSION"
          fi
       else
-         VERSION="`get_project_version "${VERSIONFILE}" "${VERSIONNAME}"`" || exit 1
+         VERSION="`get_project_version "${VERSIONFILE}" "${VERSIONNAME}"`"
          if [ -z "${VERSION}" ]
          then
-            VERSION="`get_project_version "src/version.h" "${VERSIONNAME}"`" || exit 1
+            VERSION="`get_project_version "src/version.h" "${VERSIONNAME}"`"
             if [ ! -z "${VERSION}" ]
             then
                VERSIONFILE="src/version.h"
@@ -196,6 +173,8 @@ Hint: specify VERSIONNAME, VERSIONFILE in mulle-project/version-info.sh"
 
 edit_version_if_requested()
 {
+   log_entry "edit_version_if_requested" "$@"
+
    if [ -z "${OPTION_VERSION_SET}" ]
    then
       [ "${OPTION_ADD_MAJOR}" -ne 0 ] &&
@@ -250,6 +229,8 @@ edit_version_if_requested()
 
 write_version_if_requested()
 {
+   log_entry "write_version_if_requested" "$@"
+
    if ! [ "${OPTION_WRITE}" = "YES" -o "${OPTION_WRITE_XCODE_VERSION}" = "YES" ]
    then
       return 1
@@ -262,15 +243,35 @@ write_version_if_requested()
 
    if [ "${OPTION_WRITE_XCODE_VERSION}" = "YES" ]
    then
-      sed -i.bak -e 's|^\([[:space:]]*CURRENT_PROJECT_VERSION[[:space:]]*=[[:space:]]*["]*\)'${XCODE_VERSION}'\(.*\)|\1'${VERSION}'\2|' "${ACTUAL_XCODEPROJ}/project.pbxproj"
+      inplace_sed -e 's|^\([[:space:]]*CURRENT_PROJECT_VERSION[[:space:]]*=[[:space:]]*["]*\)'${XCODE_VERSION}'\(.*\)|\1'${VERSION}'\2|' "${ACTUAL_XCODEPROJ}/project.pbxproj"
    fi
 
    if [ "${OPTION_WRITE}" = "YES" ]
    then
-      set_project_version "${VERSION}" "${VERSIONFILE}" "${VERSIONNAME}"
+      #
+      # small hack for extensions to distribute versioning
+      # improve with namekeys later
+      #
+      local other
+
+      set -o noglob ; IFS="
+"
+      for other in ${VERSIONFILEMIRRORS}
+      do
+         IFS="${DEFAULT_IFS}" ; set +o noglob
+
+         if [ ! -z "${other}" ]
+         then
+            set_project_version "${VERSION}" "${other}"  || exit 1
+         fi
+      done
+      IFS="${DEFAULT_IFS}" ; set +o noglob
+
+      # set mirrors first before "real", which is nicer in case of fails
+      set_project_version "${VERSION}" "${VERSIONFILE}" "${VERSIONNAME}" || exit 1
    fi
 
-   VERIFY_VERSION="`"${MULLE_EXECUTABLE_PATH}" "$@" --reset`"
+   VERIFY_VERSION="`"$0" "$@" --reset`"
 
    if [ "${VERSION}" != "${VERIFY_VERSION}" ]
    then
@@ -285,8 +286,16 @@ write_version_if_requested()
 
 parse_arguments()
 {
+   log_entry "parse_arguments" "$@"
+
    while [ $# -ne 0 ]
    do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
       case "$1" in
          --no-info)
             OPTION_READ_INFO="NO"
@@ -385,7 +394,7 @@ parse_arguments()
             OPTION_VERSIONFILE="$1"
          ;;
 
-         -h|--help)
+         -h*|--help|help)
             usage
          ;;
 
@@ -408,6 +417,8 @@ parse_arguments()
 
       shift
    done
+
+   options_setup_trace "${MULLE_TRACE}"
 
    DIRECTORY_NAME="`basename -- "$PWD"`"
 
@@ -481,10 +492,43 @@ main()
 }
 
 
-MULLE_EXECUTABLE_PATH="$0"
-MULLE_EXECUTABLE="`basename -- $0`"
-MULLE_BUILDTOOLS_FAIL_PREFIX="${MULLE_EXECUTABLE}"
+_init()
+{
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env "libexec-dir" 2> /dev/null`"
+      [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ] && \
+         echo "mulle-bashfunctions-env not installed" >&2 && \
+         exit 1
+   fi
 
-mulle_project_version_init
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || exit 1
 
+
+   #
+   # prefer local mulle-project if available
+   # Do not embed it anymore!
+   #
+   if [ -z "`command -v mulle-project-env`" ]
+   then
+      cat <<EOF >&2
+mulle-project-env not found in PATH.
+Visit the homepage for installation instructions:
+   https://github.com/mulle-nat/mulle-project
+EOF
+      exit 1
+   fi
+
+   INSTALLED_MULLE_PROJECT_VERSION="`mulle-project-env version`" || exit 1
+   MULLE_PROJECT_LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1
+
+   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-version.sh" || exit 1
+   . "${MULLE_PROJECT_LIBEXEC_DIR}/mulle-git.sh" || exit 1
+}
+
+
+
+_init "$@"
 main "$@"
+
+
