* moved to mulle-bashfunction 4.0

diff --git a/mulle-project-add-missing-branch-identifier b/mulle-project-add-missing-branch-identifier
--- a/mulle-project-add-missing-branch-identifier
+++ b/mulle-project-add-missing-branch-identifier
@@ -48,8 +48,6 @@ EOF
 }
 
 
-
-
 search_and_replace()
 {
    log_entry "search_and_replace" "$@"
@@ -65,10 +63,10 @@ search_and_replace()
    #
    lines="`get_dependency_address_nodetype_branch_tag_url`"
 
-   set -o noglob; IFS=$'\n'
+   shell_disable_glob; IFS=$'\n'
    for line in ${lines}
    do
-      set +o noglob; IFS="${DEFAULT_IFS}"
+      shell_enable_glob; IFS="${DEFAULT_IFS}"
 
       local _address
       local _nodetype
@@ -186,7 +184,7 @@ search_and_replace()
       fi
    done
 
-   set +o noglob; IFS="${DEFAULT_IFS}"
+   shell_enable_glob; IFS="${DEFAULT_IFS}"
 }
 
 
@@ -270,7 +268,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    search_and_replace "${OPTION_USERS}" "${OPTION_REPOS}"
 }
@@ -280,13 +278,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
-
 _init()
 {
    #
@@ -317,7 +308,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -337,8 +328,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    call_main "${MULLE_PROJECT_ADD_MISSING_BRANCH_IDENTIFIER_FLAGS}" "$@"
 }
diff --git a/mulle-project-all b/mulle-project-all
--- a/mulle-project-all
+++ b/mulle-project-all
@@ -1,6 +1,67 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
 [ "${TRACE}" = 'YES' -o "${SHELL_ALL_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
+
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 
 print_flags()
@@ -35,9 +96,11 @@ Usage:
    mulle-project-all [flags] ...
 
    Execute a command in all projects that are defined by the file "REPOS"
-   in the current directory. Can also traverse tests and subprojects.
+   in the current directory. Can also traverse tests and subprojects. If there
+   is no "REPOS" file, mulle-project-all will look for mulle-sde projects
+   that reside in (but exluding) the current working directory.
 
-   Can execute commands in parallel on all input repositories.
+   Can execute commands in parallel on all repositories.
 
 Example:
    mulle-project-all -p --output-no-header pwd
@@ -236,7 +299,7 @@ parallel_execute_argument_first()
 
    local argument
 
-   set -o noglob;  IFS=$'\n'
+   shell_disable_glob;  IFS=$'\n'
    for argument in ${arguments}
    do
       if [ ! -z "${argument}" ]
@@ -246,7 +309,7 @@ parallel_execute_argument_first()
             continue
          fi
 
-         set +o noglob; IFS="${DEFAULT_IFS}"
+         shell_enable_glob; IFS="${DEFAULT_IFS}"
 
          wait_for_available_job "${_parallel_maxjobs}"
          _parallel_jobs=$(($_parallel_jobs + 1))
@@ -259,7 +322,7 @@ parallel_execute_argument_first()
       fi
    done
 
-   set +o noglob; IFS="${DEFAULT_IFS}"
+   shell_enable_glob; IFS="${DEFAULT_IFS}"
 
    _parallel_end
 }
@@ -326,11 +389,11 @@ main()
          ;;
 
          --tests|--tests-only)
-            OPTION_MODE='no-main,no-subprojects'
+            OPTION_MODE='no-main,no-subprojects,no-others'
          ;;
 
          -m|--main-project-only|--project-only)
-            OPTION_MODE='no-tests,no-subprojects'
+            OPTION_MODE='no-tests,no-subprojects,no-others'
          ;;
 
          --no-project|--no-main-project)
@@ -380,16 +443,19 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    local reposfile 
    local repos 
 
    reposfile="${OPTION_REPOSFILE:-REPOS}"
-   repos="`rexekutor egrep -v '^#' "${reposfile}"`"
-   if [ -z "${repos}" ]
+   if [ -f "${reposfile}" ]
    then
-      fail "No \"${reposfile}\" file found (${PWD})" 
+      repos="`rexekutor egrep -v '^#' "${reposfile}"`"
+   else
+      shell_enable_nullglob
+      repos="`ls -1d */.mulle/share/sde | sed -e "s/\/\.mulle\/share\/sde$//" `"
+      shell_disable_nullglob
    fi
 
    if [ "${OPTION_PARALLEL}" = 'YES' ]
@@ -421,13 +487,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
-
 _init()
 {
    #
@@ -458,7 +517,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -473,8 +532,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    call_main "${MULLE_REPLACE_FLAGS}" "$@"
 }
diff --git a/mulle-project-distcheck b/mulle-project-distcheck
--- a/mulle-project-distcheck
+++ b/mulle-project-distcheck
@@ -1,4 +1,4 @@
-#! /usr/bin/env bash
+#! /bin/sh
 #
 #   Copyright (c) 2019 nat - Mulle kybernetiK
 #   All rights reserved.
@@ -31,6 +31,66 @@
 #
 [ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 MULLE_EXECUTABLE_VERSION="0.0.1s"
 
@@ -183,7 +243,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    local project_version
    local releasenotes_version
@@ -309,12 +369,6 @@ mulle-project-distribute"
 ###
 ### INIT
 ###
-trap_fail()
-{
-   exit 1
-}
-
-
 _init()
 {
    #
@@ -335,7 +389,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -348,8 +402,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 }
 
 ###
@@ -358,5 +412,8 @@ _init()
 ########
 
 
+MULLE_EXECUTABLE="${MULLE_EXECUTABLE:-${BASH_SOURCE[0]:-${(%):-%x}}}"
+
 _init "$@" # needs params
+
 main "$@"
diff --git a/mulle-project-release-entry b/mulle-project-release-entry
--- a/mulle-project-release-entry
+++ b/mulle-project-release-entry
@@ -1,47 +1,414 @@
-#! /usr/bin/env bash
+#! /bin/sh
+
+[ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_RELEASEENTRY_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
+
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
 
 
-# get latest release
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
-main()
+MULLE_EXECUTABLE_VERSION="0.0.0"
+
+
+print_flags()
 {
-   local commit
+   echo "   -f    : force operation"
+
+   ##
+   ## ADD YOUR FLAGS DESCRIPTIONS HERE
+   ##
+
+   options_technical_flags_usage \
+                " : "
+}
+
+
+usage()
+{
+   [ $# -ne 0 ] && log_error "$*"
+
+
+   cat <<EOF >&2
+Usage:
+   mulle-project-releaseentry [flags]
+
+   Emit a markdown line with a hyperlink to the RELEASENOTES.md
+
+Flags:
+EOF
+   print_flags | LC_ALL=C sort >&2
+
+   exit 1
+}
+
+convert_datestring_to_timestamp()
+{
+   date -d"$(sed -r 's#(.{4})(.{2})(.{2})(.{2})(.{2})#\1/\2/\3 \4:\5:#' <<< "${datestring}")" "+%s"
+}
+
+
+convert_date_to_timestamp()
+{
+   local year="$1"
+   local month="$2"
+   local day="$3"
+   local hour="$4"
+   local minute="$5"
+   local second="$6"
+
+   local datestring
+
+   # this gets a timestamp of 0 with default values if on UTC, but
+   # will change with timezone!
+   printf -v datestring "%04d%02d%02d%02d%02d%02d" "${year:-1970}" \
+                                                   "${month:-1}" \
+                                                   "${day:-1}" \
+                                                   "${hour:-0}" \
+                                                   "${minute:-0}" \
+                                                   "${second:-0}"
+
+   date -d"$(sed -r 's#(.{4})(.{2})(.{2})(.{2})(.{2})#\1/\2/\3 \4:\5:#' <<< "${datestring}")" "+%s"
+}
+
+
+emit_line()
+{
+   local version="$1"
+   local tag="$2"
+
+   local repo
+   local user
+   local dir
+
+   dir="${PWD}"
+
+   repo="`mulle-sde env get PROJECT_NAME 2> /dev/null`"
+   if [ -z "${repo}" ]
+   then
+      repo="`basename -- "${dir}" `"
+   fi
+   dir="`dirname -- "${dir}" `"
+   user="`basename -- "${dir}" `"
+
+   case "${user}" in
+      srcS)
+         user="mulle-sde"
+      ;;
+   esac
+
+   echo "[${repo}](//github.com/${user}/${repo}/RELEASENOTES.md) | ${version} | ${tag:--}"
+}
+
+
+git_numeric_tags_sorted_by_time()
+{
+   log_entry git_numeric_tags_sorted_by_time "$@"
+
+   rexekutor git tag --sort=committerdate \
+   | egrep '^[0-9]*\.[0-9]*\.[0-9]*$'
+}
+
+
+git_numeric_tags_in_timerange()
+{
+   log_entry git_numeric_tags_in_timerange "$@"
+
+   local timestamp1="$1"
+   local timestamp2="$2"
+
+   local tags
+
+   tags="`git_numeric_tags_sorted_by_time`"
+   if [ -z "${timestamp1}" -a -z "${timestamp2}" ]
+   then
+      if [ ! -z "${tags}" ]
+      then
+         printf '%s\n' "${tags}"
+      fi
+      return
+   fi
+
    local tag
+   local timestamp
+
+   while :
+   do
+      if ! read -r tag
+      then
+         break
+      fi
+
+      timestamp="`rexekutor git log -1 --format="%at" "${tag}"`"
+      if [ ! -z "${timestamp1}" ] && [ "${timestamp}" -lt "${timestamp1}" ]
+      then
+         log_debug "tag \"${tag}\" with timestamp ${timestamp} is out of range ${timestamp1}-${timestamp2}"
+         continue
+      fi
+
+      if [ ! -z "${timestamp2}" ] && [ "${timestamp}" -ge "${timestamp2}" ]
+      then
+         log_debug "tag \"${tag}\" with timestamp ${timestamp} is out of range ${timestamp1}-${timestamp2}"
+         continue
+      fi
+      echo "${tag}"
+   done <<< "${tags}"
+}
+
+
+run()
+{
+   log_entry run "$@"
+
+   local timestamp1="$1"
+   local timestamp2="$2"
+
    local version
+
+   version="`mulle-project-version -s`"
+   if [ -z "${version}" ]
+   then
+      fail "No project version found in \"${PWD}\""
+   fi
+
    #
    # get commit tagged as "latest" (assume its the old version and latest
    # has not been tagged yet)
    #
-   commit="`git rev-list -n 1 latest`"
-   if [ ! -z "${commit}" ]
+   local latest_commit
+
+   latest_commit="`rexekutor git rev-list -n 1 latest --`"
+   if [ -z "${latest_commit}" ]
    then
-      tag="`git tag -l --points-at "${commit}" \
-            | sort -r -n \
-            | egrep '[0-9]*\.[0-9]*\.[0-9]*' | head -1`"
+      emit_line "${version}"
+      return
    fi
 
-   version="`mulle-project-version -s`"
+   local tag
+   local version_commit
 
-   if [ ! -z "${version}" ]
+   #
+   # if there is a commit for the version already, latest is probably boring
+   # and version as well as its the latest. Guess last one from timestamp
+   #
+   version_commit="`rexekutor git rev-list -n 1 "${version}" -- 2> /dev/null`"
+   if [ ! -z "${version_commit}" ]
    then
-      local repo
-      local user
-      local dir
+      tag="`git_numeric_tags_in_timerange "${timestamp1}" "${timestamp2}" \
+            | tail -1 `"
+      tag="${tag:-???}"
+   else
+      tag="`rexekutor git tag -l --points-at "${latest_commit}" \
+            | sort -r -n \
+            | egrep '^[0-9]*\.[0-9]*\.[0-9]*$' | head -1`"
+   fi
 
-      dir="${PWD}"
+   emit_line "${version}" "${tag}"
+}
 
-      repo="`basename -- "${dir}" `"
-      dir="`dirname -- "${dir}" `"
-      user="`basename -- "${dir}" `"
 
-      case "${user}" in
-         srcS)
-            user="mulle-sde"
+main()
+{
+   local MULLE_FLAG_MAGNUM_FORCE='NO'
+
+   # technical flags
+   local MULLE_TRACE
+   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
+   local MULLE_FLAG_LOG_LOCAL='NO'
+   local MULLE_FLAG_LOG_DEBUG='NO'
+   local MULLE_FLAG_LOG_EXEKUTOR='NO'
+   local MULLE_FLAG_LOG_FLUFF='NO'
+   local MULLE_FLAG_LOG_SCRIPTS='NO'
+   local MULLE_FLAG_LOG_SETTINGS='NO'
+   local MULLE_FLAG_LOG_VERBOSE='NO'
+   local MULLE_FLAG_LOG_MERGE='NO'
+   local MULLE_TRACE_POSTPONE='NO'
+
+   local OPTION_PREVIOUS_RELEASE_DATE
+
+   #
+   # simple flag handling
+   #
+   while [ $# -ne 0 ]
+   do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -f|--force)
+            MULLE_FLAG_MAGNUM_FORCE='YES'
+         ;;
+
+         -h*|--help|help)
+            usage
+         ;;
+
+
+         --version)
+            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
+            exit 0
+         ;;
+
+         -p|--previous-release-date)
+            [ $# -eq 1 ] && fail "missing argument to $1"
+            shift
+
+            OPTION_PREVIOUS_RELEASE_DATE="$1"
+         ;;
+
+         -*)
+            usage "Unknown flag \"$1\""
+         ;;
+
+         *)
+            break
          ;;
       esac
 
-      echo "[${repo}](//github.com/${user}/${repo}/RELEASENOTES.md) | ${version} | ${tag:--} |"
+      shift
+   done
+
+   options_setup_trace "${MULLE_TRACE}" && set -x
+
+   if [ -z "${OPTION_PREVIOUS_RELEASE_DATE}" ]
+   then
+      run
+      return $?
    fi
+
+   local timestamp1
+   local timestamp2
+
+   # remove timezone, date can't parse it
+   OPTION_PREVIOUS_RELEASE_DATE="${OPTION_PREVIOUS_RELEASE_DATE%[+-][0-9][0-9][0-9][0-9]}"
+
+   datestring="`date -d "${OPTION_PREVIOUS_RELEASE_DATE}" +'%Y%m%d%H%M%S' `"
+   timestamp1="`convert_datestring_to_timestamp "${datestring}" `" || return 1
+
+   # give it + 2days
+   timestamp2=$(( timestamp1 + 7200 * 7 ))
+
+   # we want to ignore commits after this timestamp
+   run "" "${timestamp2}"
 }
 
-main "$@" | sort
+
+########
+###
+### INIT - You usually won't edit code below
+###
+_init()
+{
+   #
+   # minimal setup exit
+   #
+   if [ "$1" = "version" ]
+   then
+      printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
+      exit 0
+   fi
+
+   #
+   # leading backslash ? looks like we're getting called from
+   # mingw via a .BAT or so
+   #
+   case "$PATH" in
+      '\\'*)
+         PATH="${PATH//\\/\/}"
+      ;;
+   esac
+
+   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+   then
+      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
+      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+      then
+         if [ -z "`command -v "${executablepath}"`" ]
+         then
+            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+         else
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
+         fi
+         exit 1
+      fi
+   fi
+
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" &&
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh" &&
+   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh" ||
+      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
+
+   #  set -e # more pain then gain in the end
+   #  set -u # doesn't work with my style
+
+   shell_enable_pipefail
+   shell_enable_extglob
+
+   call_main "${MULLE_PROJECT_RELEASEENTRY_FLAGS}" "$@"
+}
+
+
+_init "$@" # will call main indirectly via call_main
+
+###
+### INIT
+###
+########
diff --git a/mulle-project-sourcetree-doctor b/mulle-project-sourcetree-doctor
--- a/mulle-project-sourcetree-doctor
+++ b/mulle-project-sourcetree-doctor
@@ -1,7 +1,67 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
 [ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_SOURCETREE_DOCTOR_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 MULLE_EXECUTABLE_VERSION="0.0.0"
 
@@ -94,7 +154,7 @@ __doctor_archive_nodeline()
             fi
 
             case "${user}" in
-               mulle-c|mulle-objc|mulle-core|mulle-concurrent|MulleWeb|MulleFoundation|MulleUI)
+               codeon-gmbh|mulle-c|mulle-objc|mulle-core|mulle-concurrent|MulleEOF|MulleWeb|MulleFoundation|MulleUI)
                ;;
 
                mulle-nat)
@@ -127,6 +187,34 @@ __doctor_archive_nodeline()
 }
 
 
+r_count_character()
+{
+   local s="$1"
+   local c="$2"
+
+   RVAL="${s//[^${c}]/}"
+   RVAL="${#RVAL}"
+}
+
+
+is_balanced_character_pair()
+{
+   local s="$1"
+   local pair="$2"
+
+   local n
+   local m
+
+   r_count_character "${s}" "${pair:0:1}"
+   n="${RVAL}"
+
+   r_count_character "${s}" "${pair:1:1}"
+   m="${RVAL}"
+
+   [ $n -eq $m ]
+}
+
+
 doctor_nodeline()
 {
    log_entry "doctor_nodeline" "$@"
@@ -146,6 +234,23 @@ doctor_nodeline()
 
    nodeline_parse "${nodeline}"
 
+   if ! is_balanced_character_pair "${_branch}" "{}"
+   then
+      log_warning "${_address}: branch ${branch} has unbalanced {} characters"
+   fi
+   if ! is_balanced_character_pair "${_tag}" "{}"
+   then
+      log_warning "${_address}: tag ${_tag} has unbalanced {} characters"
+   fi
+   if ! is_balanced_character_pair "${_nodetype}" "{}"
+   then
+      log_warning "${_address}: nodetype ${_nodetype} has unbalanced {} characters"
+   fi
+   if ! is_balanced_character_pair "${_url}" "{}"
+   then
+      log_warning "${_address}: nodetype ${_url} has unbalanced {} characters"
+   fi
+
    local upcaseid
 
    r_basename "${_address}"
@@ -154,7 +259,7 @@ doctor_nodeline()
 
    if find_line "${UPCASEIDS}" "${upcaseid}"
    then
-      log_warning "${_address}: UPCASEID is a duplicate of another address"
+      log_warning "${_address}: ${upcaseid} is a duplicate of another address"
    else
       r_add_line "${UPCASEIDS}" "${upcaseid}"
       UPCASEIDS="${RVAL}"
@@ -234,7 +339,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    MULLE_SOURCETREE_LIBEXEC_DIR="`mulle-sourcetree libexec-dir`" || return 1
 
@@ -253,14 +358,14 @@ main()
    local nodeline
 
    nodelines="`cfg_read "${1:-/}" `" || exit 1
-   set -o noglob ; IFS=$'\n'
+   shell_disable_glob ; IFS=$'\n'
    for nodeline in ${nodelines}
    do
-      IFS="${DEFAULT_IFS}" ; set +o noglob
+      IFS="${DEFAULT_IFS}" ; shell_enable_glob
 
       doctor_nodeline "${nodeline}"
    done
-   IFS="${DEFAULT_IFS}" ; set +o noglob
+   IFS="${DEFAULT_IFS}" ; shell_enable_glob
 }
 
 
@@ -268,13 +373,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
-
 _init()
 {
    #
@@ -305,7 +403,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -319,8 +417,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    call_main "${MULLE_PROJECT_SOURCETREE_DOCTOR_FLAGS}" "$@"
 }
diff --git a/mulle-project-sourcetree-update-tags b/mulle-project-sourcetree-update-tags
--- a/mulle-project-sourcetree-update-tags
+++ b/mulle-project-sourcetree-update-tags
@@ -1,6 +1,67 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
 [ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_SOURCETREE_UPDATE_TAGS_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
+
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 
 MULLE_EXECUTABLE_VERSION="0.0.2"
@@ -58,7 +119,7 @@ print_commands()
       log_warning "Could not locate the stash directory. H"
    fi
 
-   set -f
+   shell_disable_glob
    IFS=$'\n'
    for line in `rexekutor mulle-sde dependency list -- \
                                                     --dedupe-mode url-filename \
@@ -116,7 +177,7 @@ print_commands()
    done
 
    IFS="${DEFAULT_IFS}"
-   set +f
+   shell_enable_glob
 }
 
 
@@ -198,7 +259,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
 
    directory="`rexekutor mulle-sde project-dir`"
@@ -231,7 +292,7 @@ main()
       if [ "${OPTION_EXECUTE_COMMANDS}" = 'YES' ]
       then
          local line
-         set -f
+         shell_disable_glob
 
          IFS=$'\n'
          for line in ${text}
@@ -240,7 +301,7 @@ main()
          done
 
          IFS="${DEFAULT_IFS}"
-         set +f
+         shell_enable_glob
       fi
    fi
 }
@@ -251,13 +312,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
-
 _init()
 {
    #
@@ -288,7 +342,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -302,8 +356,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    call_main "${MULLE_PROJECT_PACKAGE_JSON_FLAGS}" "$@"
 }
diff --git a/mulle-project-travis-ci-prerelease b/mulle-project-travis-ci-prerelease
--- a/mulle-project-travis-ci-prerelease
+++ b/mulle-project-travis-ci-prerelease
@@ -1,7 +1,67 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
 [ "${TRACE}" = 'YES' -o "${MULLE_PROJECT_TRAVIS_CI_PRERELEASE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 MULLE_EXECUTABLE_VERSION="0.0.0"
 
@@ -80,10 +140,10 @@ produce_environment()
    #
    lines="`get_dependency_address_nodetype_branch_tag_url -r`"
 
-   set -o noglob; IFS=$'\n'
+   shell_disable_glob; IFS=$'\n'
    for line in ${lines}
    do
-      set +o noglob; IFS="${DEFAULT_IFS}"
+      shell_enable_glob; IFS="${DEFAULT_IFS}"
 
       [ -z "${line}" ] && continue
 
@@ -152,7 +212,7 @@ produce_environment()
                   set "${_branch_identifier}" "${mapped_branch}" "${_address} branch: ${_branch}"
    done
 
-   set +o noglob; IFS="${DEFAULT_IFS}"
+   shell_enable_glob; IFS="${DEFAULT_IFS}"
 }
 
 
@@ -259,7 +319,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    produce_environment "${OPTION_BRANCH:-prerelease}" \
                        "${OPTION_SCOPE:-host-travis-ci-${OPTION_BRANCH:-prerelease}}" \
@@ -272,12 +332,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
 
 _init()
 {
@@ -309,7 +363,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -323,8 +377,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    INSTALLED_MULLE_PROJECT_VERSION="`mulle-project-env version`" || exit 1
    MULLE_PROJECT_LIBEXEC_DIR="`mulle-project-env libexec-dir`" || exit 1
diff --git a/mulle-replace b/mulle-replace
--- a/mulle-replace
+++ b/mulle-replace
@@ -1,7 +1,68 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
 [ "${TRACE}" = 'YES' -o "${MULLE_REPLACE_TRACE}" = 'YES' ] && set -x && : "$0" "$@"
 
+
+####
+#
+# Prelude to be placed at top of each script. Rerun this script either in
+# bash or zsh, if not already running in either (which can happen!)
+# Allows script to run on systems that either have bash (linux) or
+# zsh (macOS) only by default.
+
+if [ "$1" != --no-auto-shell ]
+then
+   if [ -z "${BASH_VERSION}" -a -z "${ZSH_VERSION}" ]
+   then
+      exe_shell="`command -v "bash" `"
+      exe_shell="${exe_shell:-`command -v "zsh" `}"
+
+      script="$0"
+
+      #
+      # Quote incoming arguments for shell expansion
+      #
+      args=""
+      for arg in "$@"
+      do
+         # True bourne sh doesn't know ${a//b/c} and <<<
+         case "${arg}" in
+            *\'*)
+               # Use cat instead of echo to avoid possible echo -n
+               # problems. Escape single quotes in string.
+               arg="`cat <<EOF | sed -e s/\'/\'\\\"\'\\\"\'/g
+${arg}
+EOF
+`"
+            ;;
+         esac
+         if [ -z "${args}" ]
+         then
+            args="'${arg}'"
+         else
+            args="${args} '${arg}'"
+         fi
+      done
+
+      #
+      # bash/zsh will use arg after -c <arg> as $0, convenient!
+      #
+
+      exec "${exe_shell:-bash}" -c ". ${script} --no-auto-shell ${args}" "${script}"
+   fi
+   if [ ! -z "${BASH_VERSION}" ]
+   then
+      set +o posix
+   fi
+else
+   shift    # get rid of --no-auto-shell
+fi
+
+
+#
+# Main script to follow, runs now either in zsh or bash
+#
+####
 
 MULLE_EXECUTABLE_VERSION="0.0.0"
 
@@ -9,6 +70,7 @@ MULLE_EXECUTABLE_VERSION="0.0.0"
 print_flags()
 {
    echo "   -f          : force operation"
+   echo "   --          : skip options"
 
    ##
    ## ADD YOUR FLAG DESCRIPTION HERE
@@ -28,7 +90,8 @@ Usage:
    mulle-replace [flags] <find> <replace> <file>
 
    Replace a string with another string in a file.
-
+   Use -f flag for protect files.
+   
 Flags:
 EOF
    print_flags | LC_ALL=C sort >&2
@@ -85,6 +148,10 @@ main()
             exit 0
          ;;
 
+         --)
+            shift
+            break
+         ;;
 
          ##
          ## ADD YOUR FLAGS HERE
@@ -102,7 +169,7 @@ main()
       shift
    done
 
-   options_setup_trace "${MULLE_TRACE}"
+   options_setup_trace "${MULLE_TRACE}" && set -x
 
    [ $# -lt 3 ] && usage "missing argument" 
 
@@ -141,7 +208,27 @@ main()
       return $?
    fi
 
+   local unprotect
+
+   if [ "${MULLE_FLAG_MAGNUM_FORCE}" = 'YES' -a ! -w "${filename}" ]
+   then
+      unprotect='YES'
+   fi
+
+   local permissions
+
+   if [ "${unprotect}" = 'YES' ]
+   then
+      permissions="`lso "${filename}"`"
+      rexekutor chmod +w "${filename}"
+   fi
+
    inplace_sed "s/${escaped_find}/${escaped_replace}/${OPTION_SED}" "${filename}" || return 1
+
+   if [ "${unprotect}" = 'YES' ]
+   then
+      rexekutor chmod "${permissions}" "${filename}"
+   fi
 
    if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
    then
@@ -155,12 +242,6 @@ main()
 ###
 ### INIT - You usually won't edit code below
 ###
-
-trap_fail()
-{
-   exit 1
-}
-
 
 _init()
 {
@@ -192,7 +273,7 @@ _init()
          then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
          else
-            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
+            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env (${PWD}})" >&2
          fi
          exit 1
       fi
@@ -206,8 +287,8 @@ _init()
    #  set -e # more pain then gain in the end
    #  set -u # doesn't work with my style
 
-   trap trap_fail INT
-   set -o pipefail
+   shell_enable_pipefail
+   shell_enable_extglob
 
    call_main "${MULLE_REPLACE_FLAGS}" "$@"
 }
