* new command mulle-project-gitignore fixes for zsh and other changes in mulle-bashfunctions

diff --git a/mulle-project-all b/mulle-project-all
--- a/mulle-project-all
+++ b/mulle-project-all
@@ -16,7 +16,7 @@ MULLE_EXECUTABLE_VERSION="0.0.0"
 #
 # Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
 #
-if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+if ! [ ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR+x} ]
 then
    MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
    export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
@@ -26,7 +26,7 @@ fi
 # The booter reruns the executable either with bash or zsh, whatever the
 # system provides. On the second run --no-auto-shell will be set first.
 #
-if [ "$1" != --no-auto-shell ]
+if [ "${1:-}" != --no-auto-shell ]
 then
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
 else
@@ -68,9 +68,10 @@ print_flags()
    cat <<EOF
    --all               : execute in all projects,subprojects,tests
    --eval              : evaluate command line, requires tricky quoting though
+   --if <expr>         : ignore project if shell expression evaluates to false
    --ignore <name>     : ignore a project from REPOS, multiples are possible
    --others            : also execute in other projects, like demo
-   --sde               : skip repositories that are mulle-sde projects
+   --sde               : only execute in mulle-sde projects
    --output-no-header  : don't visually separate command output
    --parallel          : execute operations in parallel
    --repos-file <f>    : REPOS file to use
@@ -128,9 +129,14 @@ Usage:
       OTHER_NAME      : set if its an other project test
       TEST_NAME       : set if its a test
 
+   These values are alsot available in the --if expression.
+
 Examples:
    List git status of all projects:
       mulle-project-all --parallel --output-no-header git status -s
+
+   Create a .gitattributes file for projects under git control:
+      mulle-project-all --if "[ -d .git ]" cp /tmp/.gitattributes .
 
    Generate hacky include statements for all projects:
       mulle-project-all -s --eval printf '%s\\\\n' '\#include\ \<\${NAME}.h\>'
@@ -161,7 +167,7 @@ EOF
 
 shell_it()
 {
-   log_entry "shell_it" "$1" ...
+   log_entry "shell_it" "$@"
 
    [ -z "$1" ] && return
 
@@ -170,6 +176,20 @@ shell_it()
 
       r_basename "$1"
       NAME="$RVAL"
+
+      if [ ! -z "${OPTION_IF}" ]
+      then
+         if ! NAME="'${NAME}'" \
+              PROJECT_NAME="'${PROJECT_NAME}'" \
+              SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
+              OTHER_NAME="'${OTHER_NAME}'" \
+              TEST_NAME="'${TEST_NAME}'" \
+              eval_exekutor "${OPTION_IF}"
+         then
+            log_info "Skip ${C_RESET_BOLD}$1"
+            return
+         fi
+      fi
 
       case ",${OPTION_ADORN}," in
          *,no-bar,*|*,no-top-bar,*|*,none,*)
@@ -205,9 +225,10 @@ shell_it()
 
       shift
 
+
       if [ "${OPTION_EVAL}" = 'YES' ]
       then
-         eval_exekutor NAME="'${RVAL}'" \
+         eval_exekutor NAME="'${NAME}'" \
                        PROJECT_NAME="'${PROJECT_NAME}'" \
                        SUBPROJECT_NAME="'${SUBPROJECT_NAME}'" \
                        OTHER_NAME="'${OTHER_NAME}'" \
@@ -268,8 +289,8 @@ project_it()
                         ) `"
 
          old="${SUBPROJECT_NAME}"
-         for subproject in ${subprojects}
-         do
+         .foreachpath subproject in ${subprojects}
+         .do
             case "${subproject}" in
                craftinfo/*)
                   # ignore
@@ -284,7 +305,7 @@ project_it()
                   fi
                ;;
             esac
-         done
+         .done
 
          SUBPROJECT_NAME="${old}"
       ;;
@@ -296,14 +317,12 @@ project_it()
          local test 
 
          tests="`( cd "${project}" ; mulle-env --search-here environment \
-                                       get MULLE_SDE_TEST_PATH 2> /dev/null )`"
+                                       get --lenient MULLE_SDE_TEST_PATH 2> /dev/null )`"
          tests="${tests:-test}"
 
          old="${TEST_NAME}"
-         IFS=':'
-         for test in ${tests}
-         do
-            IFS="${DEFAULT_IFS}"
+         .foreachpath test in ${tests}
+         .do
             if [ -d "${project}/${test}" ]
             then
                TEST_NAME="${test}"
@@ -313,8 +332,7 @@ project_it()
                   exit 1
                fi
             fi
-         done
-         IFS="${DEFAULT_IFS}"
+         .done
 
          TEST_NAME="${old}"
       ;;
@@ -330,18 +348,15 @@ project_it()
          others="${others:-demo}"
 
          old="${OTHER_NAME}"
-         IFS=':'
-         for other in ${others}
-         do
-            IFS="${DEFAULT_IFS}"
+         .foreachpath other in ${others}
+         .do
             if [ -d "${project}/${other}" ]
             then
                OTHER_NAME="${other}"
 
                project_it "${project}/${other}" "${mode}" "$@"
             fi
-         done
-         IFS="${DEFAULT_IFS}"
+         .done
 
          OTHER_NAME="${old}"
       ;;
@@ -364,7 +379,7 @@ parallel_execute_argument_first()
    local _parallel_jobs
    local _parallel_fails
 
-   [ $# -eq 0 ] && internal_fail "missing commandline"
+   [ $# -eq 0 ] && _internal_fail "missing commandline"
 
    _parallel_begin
 
@@ -419,7 +434,7 @@ main()
    local OPTION_PARALLEL
    local OPTION_SDE_TEST='NO'
    local OPTION_EVAL
-
+   local OPTION_IF
    local OPTION_IGNORE
 
    #
@@ -453,6 +468,23 @@ main()
 
             r_add_line "${OPTION_IGNORE}" "$1"
             OPTION_IGNORE="${RVAL}"
+         ;;
+
+         --if)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            r_concat "${OPTION_IF}" "$1" "&&"
+            OPTION_IF="${RVAL}"
+         ;;
+
+
+         --if-exists)
+            [ $# -eq 1 ] && fail "missing parameter for \"$1\""
+            shift
+
+            r_concat "${OPTION_IF}" "[ -e \"$1\" ]"
+            OPTION_IF="${RVAL}"
          ;;
 
          -l|--lenient)
diff --git a/mulle-replace b/mulle-replace
--- a/mulle-replace
+++ b/mulle-replace
@@ -16,7 +16,7 @@ MULLE_EXECUTABLE_VERSION="0.0.0"
 #
 # Figure out MULLE_BASHFUNCTIONS_LIBEXEC_DIR on this machine if needed.
 #
-if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
+if ! [ ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR+x} ]
 then
    MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
    export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
@@ -26,7 +26,7 @@ fi
 # The booter reruns the executable either with bash or zsh, whatever the
 # system provides. On the second run --no-auto-shell will be set first.
 #
-if [ "$1" != --no-auto-shell ]
+if [ "${1:-}" != --no-auto-shell ]
 then
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
 else
@@ -58,7 +58,9 @@ MULLE_EXECUTABLE="${BASH_SOURCE[0]:-${(%):-%x}}"
 
 print_flags()
 {
-   echo "   -f          : force operation"
+   echo "   -f          : force operation on protected files"
+   echo "   -1          : replace only once per line"
+   echo "   --regex     : use sed regexp"
    echo "   --          : skip options"
 
    ##
@@ -79,7 +81,9 @@ Usage:
    mulle-replace [flags] <find> <replace> <file>
 
    Replace a string with another string in a file.
-   Use -f flag for protect files.
+
+   You will need to escape the '/' characters, if you choose the --regex
+   option.
    
 Flags:
 EOF
@@ -89,97 +93,92 @@ EOF
 }
 
 
-main()
+
+delete_line()
 {
-   local MULLE_FLAG_MAGNUM_FORCE='NO'
+   log_entry delete_line "$@"
 
-   # technical flags
-   local MULLE_TRACE
-   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
-   local MULLE_FLAG_LOG_LOCAL='NO'
-   local MULLE_FLAG_LOG_DEBUG='NO'
-   local MULLE_FLAG_LOG_EXEKUTOR='NO'
-   local MULLE_FLAG_LOG_FLUFF='NO'
-   local MULLE_FLAG_LOG_SCRIPTS='NO'
-   local MULLE_FLAG_LOG_SETTINGS='NO'
-   local MULLE_FLAG_LOG_VERBOSE='NO'
-   local MULLE_FLAG_LOG_MERGE='NO'
-   local MULLE_TRACE_POSTPONE='NO'
+   local find="$1"
+   local filename="$2"
 
-   local OPTION_SED=""
+   local escaped_find
 
-   #
-   # simple flag handling
-   #
-   while [ $# -ne 0 ]
-   do
-      if options_technical_flags "$1"
-      then
-         shift
-         continue
-      fi
+   if [ "${OPTION_ESCAPE}" = 'YES' ]
+   then
+      r_escaped_sed_pattern "${find}"
+      escaped_find="${RVAL}"
+   else
+      escaped_find="${find}"
+   fi
 
-      case "$1" in
-         -f|--force)
-            MULLE_FLAG_MAGNUM_FORCE='YES'
-         ;;
+   local before
+   local after
 
-         -h*|--help|help)
-            usage
-         ;;
+   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
+   then
+      before="`rexekutor cat "${filename}"`"
+   fi
 
-         -g|--global)
-            OPTION_SED="g"
-         ;;
+   if [ "${MULLE_FLAG_EXEKUTOR_DRY_RUN}" = 'YES' -a "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
+   then
+      after="`rexekutor sed "/${escaped_find}/d" "${filename}" `" || return 1
+      log_verbose "Changes"
+      rexekutor diff -b <( echo "${before}") <( echo "${after}" ) >&2
+      return $?
+   fi
 
-         --version)
-            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
-            exit 0
-         ;;
+   local unprotect
 
-         --)
-            shift
-            break
-         ;;
+   if [ "${MULLE_FLAG_MAGNUM_FORCE}" = 'YES' -a ! -w "${filename}" ]
+   then
+      unprotect='YES'
+   fi
 
-         ##
-         ## ADD YOUR FLAGS HERE
-         ##
+   local permissions
 
-         -*)
-            usage "Unknown flag \"$1\""
-         ;;
+   if [ "${unprotect}" = 'YES' ]
+   then
+      permissions="`lso "${filename}"`"
+      rexekutor chmod +w "${filename}"
+   fi
 
-         *)
-            break
-         ;;
-      esac
+   inplace_sed "/${escaped_find}/d" "${filename}" || return 1
 
-      shift
-   done
+   if [ "${unprotect}" = 'YES' ]
+   then
+      rexekutor chmod "${permissions}" "${filename}"
+   fi
 
-   options_setup_trace "${MULLE_TRACE}" && set -x
+   if [ "${MULLE_FLAG_LOG_VERBOSE}" = 'YES' ]
+   then
+      log_verbose "Changes"
+      rexekutor diff -b <( echo "${before}") "${filename}" >&2
+   fi
+}
 
-   [ $# -lt 3 ] && usage "missing argument" 
+
+replace()
+{
+   log_entry replace "$@"
 
    local find="$1"
    local replace="$2"
    local filename="$3"
 
-   shift 3
+   local escaped_find
+   local escaped_replace
 
-   [ $# -ne 0 ] && usage "superflous arguments \"$*\"" 
+   if [ "${OPTION_ESCAPE}" = 'YES' ]
+   then
+      r_escaped_sed_pattern "${find}"
+      escaped_find="${RVAL}"
 
-   [ -f "${filename}" ] || fail "File not found"
-
-   local escaped_find 
-   local escaped_replace 
-
-   r_escaped_sed_pattern "${find}"
-   escaped_find="${RVAL}"
-
-   r_escaped_sed_replacement "${replace}"
-   escaped_replace="${RVAL}"
+      r_escaped_sed_replacement "${replace}"
+      escaped_replace="${RVAL}"
+   else
+      escaped_find="${find}"
+      escaped_replace="${replace}"
+   fi
 
    local before
    local after
@@ -224,6 +223,122 @@ main()
       log_verbose "Changes"
       rexekutor diff -b <( echo "${before}") "${filename}" >&2
    fi
+}
+
+
+main()
+{
+   local MULLE_FLAG_MAGNUM_FORCE='NO'
+
+   # technical flags
+   local MULLE_TRACE
+   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
+   local MULLE_FLAG_LOG_LOCAL='NO'
+   local MULLE_FLAG_LOG_DEBUG='NO'
+   local MULLE_FLAG_LOG_EXEKUTOR='NO'
+   local MULLE_FLAG_LOG_FLUFF='NO'
+   local MULLE_FLAG_LOG_SCRIPTS='NO'
+   local MULLE_FLAG_LOG_SETTINGS='NO'
+   local MULLE_FLAG_LOG_VERBOSE='NO'
+   local MULLE_FLAG_LOG_MERGE='NO'
+   local MULLE_TRACE_POSTPONE='NO'
+
+   local OPTION_SED="g"
+   local OPTION_ESCAPE='YES'
+   local OPTION_DELETE_LINE='NO'
+
+   #
+   # simple flag handling
+   #
+   while [ $# -ne 0 ]
+   do
+      if options_technical_flags "$1"
+      then
+         shift
+         continue
+      fi
+
+      case "$1" in
+         -f|--force)
+            MULLE_FLAG_MAGNUM_FORCE='YES'
+         ;;
+
+         -h*|--help|help)
+            usage
+         ;;
+
+         -1|--once)
+            OPTION_SED=""
+         ;;
+
+         --delete-line)
+            OPTION_DELETE_LINE="YES"
+         ;;
+
+         -g|--global)
+            OPTION_SED="g"
+         ;;
+
+         --regex|--regexp)
+            OPTION_ESCAPE='NO'
+         ;;
+
+         --version)
+            printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
+            exit 0
+         ;;
+
+         --)
+            shift
+            break
+         ;;
+
+         ##
+         ## ADD YOUR FLAGS HERE
+         ##
+
+         -*)
+            usage "Unknown flag \"$1\""
+         ;;
+
+         *)
+            break
+         ;;
+      esac
+
+      shift
+   done
+
+   options_setup_trace "${MULLE_TRACE}" && set -x
+
+   if [ "${OPTION_DELETE_LINE}" = 'YES' ]
+   then
+      [ $# -lt 2 ] && usage "missing argument"
+
+      local find="$1"
+      local filename="$2"
+
+      shift 2
+
+      [ $# -ne 0 ] && usage "superflous arguments \"$*\""
+
+      [ -f "${filename}" ] || fail "File not found"
+
+      delete_line "${find}" "${filename}"
+      return $?
+   fi
+
+   [ $# -lt 3 ] && usage "missing argument"
+
+   local find="$1"
+   local replace="$2"
+   local filename="$3"
+
+   shift 3
+
+   [ $# -ne 0 ] && usage "superflous arguments \"$*\""
+
+   replace "${find}" "${replace}" "${filename}"
 }
 
 
