Improve broken installation error messages

diff --git a/mulle-homebrew-path b/mulle-homebrew-path
--- a/mulle-homebrew-path
+++ b/mulle-homebrew-path
@@ -56,7 +56,7 @@ fail()
 
 
 path="`dirname -- "$0"`"
-cd "${path}"
+cd "${path}" || exit 1
 
 
 case "$1" in
@@ -67,7 +67,10 @@ case "$1" in
    "--libexec-path")
       if [ ! -f mulle-homebrew.sh ]
       then
-         cd ../libexec/mulle-homebrew || fail "libexec not found"
+         [ ! -d "../libexec" ] && fail "libexec not found"
+         [ ! -d "../libexec/mulle-homebrew" ] && fail "libexec/mulle-homebrew is missing"
+
+         cd ../libexec/mulle-homebrew || exit 1
       fi
       pwd -P
    ;;
@@ -75,7 +78,10 @@ case "$1" in
    "--share-path")
       if [ ! -f release.sh.template ]
       then
-         cd ../share/mulle-homebrew || fail "share not found"
+         [ ! -d "../share" ] && fail "share not found"
+         [ ! -d "../share/mulle-homebrew" ] && fail "share/mulle-homebrew is missing"
+
+         cd ../share/mulle-homebrew || exit 1
       fi
       pwd -P
    ;;
@@ -83,6 +89,10 @@ case "$1" in
    "--template-path")
       if [ ! -f release.sh.template ]
       then
+         [ ! -d "../share" ]                && fail "share not found"
+         [ ! -d "../share/mulle-homebrew" ] && fail "share/mulle-homebrew is missing"
+         [ ! -f "../share/mulle-homebrew/release.sh.template" ] && fail "release.sh.template is missing"
+
          cd ../share/mulle-homebrew || fail "share not found"
       fi
       echo "`pwd -P`/release.sh.template"
