improve error messages for common problems

diff --git a/release.sh.template b/release.sh.template
--- a/release.sh.template
+++ b/release.sh.template
@@ -106,7 +106,13 @@ generate_brew_formula()
 #######
 
 MULLE_BOOTSTRAP_FAIL_PREFIX="`basename -- $0`"
-MULLE_HOMEBREW_VERSION="3.4.3"
+MULLE_HOMEBREW_VERSION="3.4.4"
+
+if [ -z "`command -v mulle-homebrew-env`" ]
+then
+   echo "mulle-homebrew-env not found in PATH" >&2
+   exit 1
+fi
 
 INSTALLED_MULLE_HOMEBREW_VERSION="`mulle-homebrew-env version`" || exit 1
 LIBEXEC_DIR="`mulle-homebrew-env libexec-path`" || exit 1
@@ -208,9 +214,13 @@ RBFILE="${RBFILE:-${NAME}.rb}"
 #
 if [ -z "${PUBLISHER}" ]
 then
-   fail "you need to specify a publisher with --publisher (hint: https://github.com/<publisher>)"
+   fail "You need to specify a publisher with --publisher (hint: https://github.com/<publisher>)"
 fi
 
+if [ -z "${VERSION}" ]
+then
+   fail "Could not figure out the version. (hint: check VERSIONNAME, VERSIONFILE)"
+fi
 
 # tag to tag your release
 TAG="${TAG:-${TAG_PREFIX}${VERSION}}"
